label variable ident "IDENT. Identifiant unique"
label variable annee "ANNEE. Année"
label variable poids "POIDS. Poids de redressement"
label variable sdsexe "SDSEXE. Sexe de l'enquêté.e"
label variable habitat "HABITAT. Catégorie d'agglomération"
label variable region "REGION. ZEAT"
label variable sdannais "SDANNAIS. Année de naissance"
label variable sdage "SDAGE. Âge"
label variable sdagetr "SDAGETR. Âge (en tranches)"
label variable sdsitua "SDSITUA. Quelle est votre situation actuellement ?"
label variable sdact "SDACT. Activité principale de l'interviewé.e (ou ancienne activité)"
label variable sdstat "SDSTAT. Statut d'activité de l'interviewé.e"
label variable sdpcs7 "SDPCS7. Profession de l'interviewé.e (ou ancienne profession) en 7 catégories"
label variable sdpcs10 "SDPCS10. Profession actuelle de l'interviewé.e en 10 catégories"
label variable sdstatemp "SDSTATEMP. Type de contrat (ou ancien type de contrat)"
label variable sdsitfam "SDSITFAM. Quelle est votre situation familiale dans le foyer ?"
label variable sdpr "SDPR. Désignation de la personne de référence"
label variable sdprsitua "SDPRSITUA. Situation de la personne de référence"
label variable sdpract "SDPRACT. Activité principale de la personne de référence (ou ancienne activité principale)"
label variable sdprstat "SDPRSTAT. Statut d'activité de la personne de référence"
label variable sdprpcs7 "SDPRPCS7. Catégorie socio-professionnelle de la personne de référence (ou Catégorie socio-professionnelle pour les retraité.es et les chômeur.euses)"
label variable sdprpcs10 "SDPRPCS10. Profession  actuelle de la personne de référence en 10 catégories"
label variable sdnbpers "SDNBPERS. Nombre de personnes dans le foyer"
label variable sdcouple "SDCOUPLE. Vivez-vous en couple ?"
label variable sdmatri "SDMATRI. Statut marital"
label variable sdnbenf "SDNBENF. Combien y-a-t-il d'enfants à charge dans votre foyer ?"
label variable sdnbadu "SDNBADU. Nombre d'adultes vivant au foyer"
label variable sduc "SDUC. Nombre d'unités de consommation du ménage"
label variable sdsplit "SDSPLIT. Version du questionnaire"
label variable sdmut "SDMUT. Êtes-vous couvert.e par une mutuelle ou une assurance complémentaire maladie ?"
label variable og1 "OG1. Vous personnellement, comment qualifieriez-vous votre situation actuelle ?"
label variable og2 "OG2. Par rapport à la situation de vos parents au même âge, diriez-vous que votre situation actuelle est."
label variable og3_1 "OG3_1. Quand vous pensez à l'avenir, êtes-vous plutôt optimiste ou plutôt pessimiste... pour vous-même ?"
label variable og3_2 "OG3_2. Quand vous pensez à l'avenir, êtes-vous plutôt optimiste ou plutôt pessimiste... pour vos enfants ou les générations futures ?"
label variable me1 "ME1. Pensez-vous pouvoir compter sur quelqu'un en cas de grave problème personnel ?"
label variable og4_1 "OG4_1. Êtes-vous personnellement préoccupé(e) par. le logement ?"
label variable og4_2 "OG4_2. Êtes-vous personnellement préoccupé(e) par. les migrations des populations des pays pauvres vers les pays riches ?"
label variable og4_3 "OG4_3. Êtes-vous personnellement préoccupé(e) par. la pauvreté ?"
label variable og4_4 "OG4_4. Êtes-vous personnellement  préoccupé(e) par. l'insécurité dans votre quartier ou votre village ?"
label variable og4_5 "OG4_5. Êtes-vous personnellement préoccupé(e) par. la dette de la France ?"
label variable og4_6 "OG4_6. Êtes-vous personnellement  préoccupé(e) par. le chômage ?"
label variable og4_7 "OG4_7. Êtes-vous personnellement  préoccupé(e) par. les crises financières internationales ?"
label variable og4_8 "OG4_8. Êtes-vous personnellement préoccupé(e) par. la santé des Français ?"
label variable og4_9 "OG4_9. Êtes-vous personnellement  préoccupé(e) par. le niveau des salaires et du pouvoir d'achat ?"
label variable og5_ab_1 "OG5_AB_1. Êtes-vous personnellement préoccupé(e) par. les problèmes liés à l'environnement ?"
label variable og5_ab_2 "OG5_AB_2. Êtes-vous personnellement préoccupé(e) par. les risques alimentaires ?"
label variable og5_ab_3 "OG5_AB_3. Êtes-vous personnellement préoccupé(e) par. le Sida ?"
label variable og5_ab_4 "OG5_AB_4.Êtes-vous personnellement préoccupé(e) par. l'avenir du système de retraite ?"
label variable og5_ab_5 "OG5_AB_5. Êtes-vous personnellement  préoccupé(e) par. le cancer ?"
label variable og5_ab_6 "OG5_AB_6. Êtes-vous personnellement préoccupé(e) par. les risques d'épidémie ?"
label variable og5_ab_7 "OG5_AB_7. Êtes-vous personnellement préoccupé(e) par. les inégalités entre les femmes et les hommes ?"
label variable og5_cd_1 "OG5_CD_1. Êtes-vous personnellement  préoccupé(e) par. les problèmes liés à l'environnement ?"
label variable og5_cd_4 "OG5_CD_4. Êtes-vous personnellement  préoccupé(e) par. l'avenir du système de retraite ?"
label variable og5_cd_7 "OG5_CD_7. Êtes-vous personnellement préoccupé(e) par. les inégalités entre les femmes et les hommes ?"
label variable og6 "OG6. Quand vous pensez à la société française telle qu'elle existe aujourd'hui, avec laquelle des opinions suivantes êtes-vous le plus d'accord ?"
label variable og7 "OG7. Pensez-vous qu'il y a trop d'intervention de l'État en matière économique et sociale, juste ce qu'il faut ou pas assez ?"
label variable og8_1 "OG8_1. « Il y a trop de travailleurs immigrés »"
label variable og8_2 "OG8_2. «  Les filles ont autant l'esprit scientifique que les garçons »"
label variable og8_3 "OG8_3. «  Les couples homosexuels peuvent assumer un rôle de parent comme les couples hétérosexuels »"
label variable og8_4 "OG8_4. «  Les femmes font de meilleures infirmières que les hommes »"
label variable og8_5 "OG8_5. «  Le mariage est le cadre idéal pour vivre une relation de couple »"
label variable og8_6 "OG8_6. «  Aujourd'hui, on se marie, on se quitte, on forme un autre foyer et les enfants s'y adaptent très bien »"
label variable og8_8 "OG8_8. «  Les mères savent mieux répondre aux besoins et attentes des enfants que les pères »"
label variable og8_9 "OG8_9. «  Dans l'idéal, les femmes devraient rester à la maison pour élever leurs enfants »"
label variable og8_11 "OG8_11. « Les hommes sont de meilleurs managers d'équipe au sein d'une entreprise que les femmes »"
label variable og9 "OG9. Selon vous, qu'est-ce qui est le plus important pour réussir dans la vie à l'heure actuelle en France ?"
label variable og10 "OG10. Chez vous, les courses, le ménage et le linge sont-ils faits..."
label variable og11 "OG11. Concernant la répartition des tâches ménagères, pensez-vous, qu'en général aujourd'hui, dans les jeunes couples."
label variable og12 "OG12. Toujours concernant la répartition des tâches ménagères, pensez-vous qu'aujourd'hui, par rapport à il y a 20 ans."
label variable og13_1 "OG13_1. Avez-vous entendu parler. du revenu de solidarité active ou RSA ?"
label variable og13_2 "OG13_2. Avez-vous entendu parler. des allocations familiales ?"
label variable og13_3 "OG13_3. Avez-vous entendu parler. de l'allocation personnalisée d'autonomie ou APA ?"
label variable og13_4 "OG13_4. Avez-vous entendu parler. de la couverture maladie universelle complémentaire ou CMU-C ?"
label variable og13_5 "OG13_5. Avez-vous entendu parler. de l'allocation pour les adultes handicapés ou AAH ?"
label variable og13_6 "OG13_6. Avez-vous entendu parler. du minimum vieillesse ou allocation de solidarité aux personnes âgées (ASPA) ?"
label variable og13_7 "OG13_7. Avez-vous entendu parler. des aides au logement ?"
label variable og13_8 "OG13_8. Avez-vous entendu parler. de la prime pour l'emploi ou PPE  ?"
label variable og13_9 "OG13_9. Avez-vous entendu parler. de l'aide à l'acquisition d'une complémentaire santé, ACS, ou « chèque-santé » ?"
label variable og13_10 "OG13_10. Avez-vous entendu parler. de l'allocation versée à des personnes victimes d'isolement social, ou ALIS ?"
label variable og13_11 "OG13_11. Avez-vous entendu parler. de l'aide médicale d'État ou AME ?"
label variable og13bis_1 "OG13BIS_1. Savez-vous qui peut bénéficier. du revenu de solidarité active ou RSA ?"
label variable og13bis_2 "OG13BIS_2. Savez-vous qui peut bénéficier . des allocations familiales ?"
label variable og13bis_3 "OG13BIS_3. Savez-vous qui peut bénéficier. de l'allocation personnalisée d'autonomie ou APA ?"
label variable og13bis_4 "OG13BIS_4. Savez-vous qui peut bénéficier. de la couverture maladie universelle complémentaire ou CMU-C ?"
label variable og13bis_5 "OG13BIS_5. Savez-vous qui peut bénéficier . de l'allocation pour les adultes handicapés ou AAH ?"
label variable og13bis_6 "OG13BIS_6. Savez-vous qui peut bénéficier. du minimum vieillesse ou allocation de solidarité aux personnes âgées (ASPA) ?"
label variable og13bis_7 "OG13BIS_7. Savez-vous qui peut bénéficier. des aides au logement ?"
label variable og13bis_8 "OG13BIS_8. Savez-vous qui peut bénéficier . de la prime pour l'emploi ou PPE  ?"
label variable og13bis_9 "OG13BIS_9. Savez-vous qui peut bénéficier. de l'aide au paiement d'une complémentaire santé, ACS, ou « chèque-santé » ?"
label variable og13bis_10 "OG13BIS_10. Savez-vous qui peut bénéficier. de l'allocation versée à des personnes victimes d'isolement social, ou ALIS ?"
label variable og13bis_11 "OG13BIS_11. Savez-vous qui peut bénéficier . de l'aide médicale d'État ou AME ?"
label variable og13ter_1 "OG13TER_1. Avez-vous entendu parler et savez-vous qui peut bénéficier. du revenu de solidarité active ou RSA ?"
label variable og13ter_2 "OG13TER_2. Avez-vous entendu parler et savez-vous qui peut bénéficier. des allocations familiales ?"
label variable og13ter_3 "OG13TER_3. Avez-vous entendu parler et savez-vous qui peut bénéficier. de l'allocation personnalisée d'autonomie ou APA ?"
label variable og13ter_4 "OG13TER_4. Avez-vous entendu parler et savez-vous qui peut bénéficier.  de la couverture maladie universelle complémentaire ou CMU-C ?"
label variable og13ter_5 "OG13TER_5. Avez-vous entendu parler et savez-vous qui peut bénéficier. de l'allocation pour les adultes handicapés ou AAH ?"
label variable og13ter_6 "OG13TER_6. Avez-vous entendu parler et savez-vous qui peut bénéficier. du minimum vieillesse ou allocation de solidarité aux personnes âgées (ASPA) ?"
label variable og13ter_7 "OG13TER_7. Avez-vous entendu parler et savez-vous qui peut bénéficier. des aides au logement ?"
label variable og13ter_8 "OG13TER_8. Avez-vous entendu parler et savez-vous qui peut bénéficier. de la prime pour l'emploi ou PPE  ?"
label variable og13ter_9 "OG13TER_9. Avez-vous entendu parler et savez-vous qui peut bénéficier. de l'aide au paiement d'une complémentaire santé, ACS, ou « chèque-santé » ?"
label variable og13ter_10 "OG13TER_10. Avez-vous entendu parler et savez-vous qui peut bénéficier. de l'allocation versée à des personnes victimes d'isolement social, ou ALIS ?"
label variable og13ter_11 "OG13TER_11. Avez-vous entendu parler et savez-vous qui peut bénéficier. de l'aide médicale d'État ou AME ?"
label variable in1 "IN1. La société française aujourd'hui, vous paraît-elle plutôt juste ou plutôt injuste ?"
label variable in2 "IN2. Globalement, depuis 5 ans, diriez-vous que les inégalités en France."
label variable in3 "IN3. À l'avenir, pensez-vous que les inégalités en France."
label variable in4_ab "IN4_AB. Quel type d'inégalité vous semble la plus répandue aujourd'hui ?"
label variable in4_cd "IN4_CD. Quel type d'inégalité vous semble la plus répandue aujourd'hui ?"
label variable in5_ab "IN5_AB. Quel type d'inégalité vous semble la moins acceptable ?"
label variable in5_cd "IN5_CD. Quel type d'inégalité vous semble la moins acceptable ?"
label variable in6 "IN6. Avez-vous le sentiment que les inégalités entre les hommes et les femmes en France sont aujourd'hui..."
label variable in7 "IN7. Depuis 10 ans, diriez-vous que les inégalités entre les hommes et les femmes ont plutôt augmenté ou plutôt diminué en France ?"
label variable in8 "IN8. Où vous placeriez-vous aujourd'hui sur cette échelle de revenus, en comparant les revenus de votre foyer avec ceux de tous les autres foyers ?"
label variable in9 "IN9. Où placeriez-vous la famille dans laquelle vous avez grandi ?"
label variable me2 "ME2. Compte tenu de vos ressources, diriez-vous que votre ménage a des difficultés pour boucler ses fins de mois ?"
label variable in10_1 "IN10_1. À votre avis, que gagne (rémunération nette mensuelle) en moyenne. un ouvrier non qualifié en usine ?"
label variable in10_2 "IN10_2. À votre avis, que devrait gagner (rémunération nette mensuelle) en moyenne. un ouvrier non qualifié en usine ?"
label variable in10_3 "IN10_3. À votre avis, que gagne (rémunération nette mensuelle) en moyenne. un médecin généraliste ?"
label variable in10_4 "IN10_4. À votre avis, que devrait gagner (rémunération nette mensuelle) en moyenne. un médecin généraliste ?"
label variable in10_5 "IN10_5. À votre avis, que gagne (rémunération nette mensuelle) en moyenne. le PDG d'une grande société française ?"
label variable in10_6 "IN10_6. À votre avis, que devrait gagner (rémunération nette mensuelle) en moyenne. le PDG d'une grande société française ?"
label variable in10_7 "IN10_7. À votre avis, que gagne (rémunération nette mensuelle) en moyenne. un enseignant en école primaire ?"
label variable in10_8 "IN10_8. À votre avis, que devrait gagner (rémunération nette mensuelle) en moyenne. un enseignant en école primaire ?"
label variable in11_1 "IN11_1. Que gagnent en moyenne les gens qui ont la même profession que vous ?"
label variable in11_2 "IN11_2. Que devraient gagner en moyenne les gens qui ont la même profession que vous ?"
label variable in12 "IN12. À partir de quel revenu mensuel diriez-vous d'une personne vivant seule qu'elle est riche ?"
label variable in13 "IN13. À partir de quel montant de patrimoine (financier et immobilier) diriez-vous d'une personne vivant seule qu'elle est riche ?"
label variable in14_1 "IN14_1. Pensez-vous qu'actuellement il faut... augmenter les impôts payés par les personnes dont le revenu est supérieur à 2500 euros par mois ?"
label variable in14_2 "IN14_2. Pensez-vous qu'actuellement il faut... interdire les rémunérations dépassant 10 000 euros par mois ?"
label variable in14_3 "IN14_3. Pensez-vous qu'actuellement il faut. réglementer les écarts de salaires dans les entreprises, pour que le salaire le plus haut ne dépasse pas dix fois le montant du salaire le plus bas ?"
label variable pe1 "PE1. Selon vous, depuis 5 ans, la pauvreté et l'exclusion en France..."
label variable pe2 "PE2. À l'avenir, pensez-vous que la pauvreté et l'exclusion en France."
label variable pe3 "PE3. Vous personnellement, pensez-vous qu'il y a un risque que vous deveniez pauvre dans les cinq prochaines années ?"
label variable pe5_1 "PE5_1. Selon vous, les personnes élevant seules leur(s) enfant(s) ont-elles un risque de pauvreté plus ou moins important que la moyenne des Français ?"
label variable pe5_2 "PE5_2. Selon vous, les familles nombreuses (trois enfants et plus) ont-elles un risque de pauvreté plus ou moins important que la moyenne des Français ?"
label variable pe5_3 "PE5_3. Selon vous, les familles avec un ou deux enfants ont-elles un risque de pauvreté plus ou moins important que la moyenne des Français ?"
label variable pe5_4 "PE5_4. Selon vous, les couples sans enfant ont-ils un risque de pauvreté plus ou moins important que la moyenne des Français ?"
label variable pe5_5 "PE5_5. Selon vous, les célibataires (sans enfant) ont-ils un risque de pauvreté plus ou moins important que la moyenne des Français ?"
label variable pe5_6 "PE5_6. Selon vous, les familles immigrées ont-elles un risque de pauvreté plus ou moins important que la moyenne des Français ?"
label variable pe4_1 "PE4_1. Selon vous, les 18-29 ans ont-ils un risque de pauvreté plus ou moins important que la moyenne des Français ?"
label variable pe4_2 "PE4_2. Selon vous, les 30-59 ans ont-ils un risque de pauvreté plus ou moins important que la moyenne des Français ?"
label variable pe4_3 "PE4_3. Selon vous, les 60-74 ans ont-ils un risque de pauvreté plus ou moins important que la moyenne des Français ?"
label variable pe4_4 "PE4_4. Selon vous, les 75 ans et plus ont-ils un risque de pauvreté plus ou moins important que la moyenne des Français ?"
label variable pe6_1 "PE6_1. Si des personnes se trouvent en situation d'exclusion ou de pauvreté, c'est parce qu'. elles ne veulent pas travailler ?"
label variable pe6_2 "PE6_2. Si des personnes se trouvent en situation d'exclusion ou de pauvreté, c'est parce qu'. elles manquent de qualifications, de diplômes, pour trouver ou retrouver un emploi ?"
label variable pe6_3 "PE6_3. Si des personnes se trouvent en situation d'exclusion ou de pauvreté, c'est parce qu'. elles n'ont pas eu de chance ?"
label variable pe6_4 "PE6_4. Si des personnes se trouvent en situation d'exclusion ou de pauvreté, c'est parce qu'. il n'y a plus assez de travail pour tout le monde ?"
label variable pe7 "PE7. Selon vous pour vivre, quel est le montant dont doit disposer au minimum un individu par mois (en euros) ?"
label variable pe16 "PE16. Selon vous, pour vivre, quel est le montant dont doit disposer au minimum un foyer comme le vôtre, par mois (en euros) ?"
label variable pe8 "PE8. D'après ce que vous en savez, quel est le montant du RSA pour une personne seule qui ne travaille pas (par mois en euros) ?"
label variable pe9 "PE9. Avec laquelle de ces opinions sur le RSA êtes-vous le plus d'accord ?"
label variable pe10 "PE10. Dans ce cas, seriez-vous prêt à accepter une hausse de vos impôts ou de vos cotisations pour financer une augmentation du RSA ?"
label variable pe17 "PE17. Sauf exception, on ne peut avoir le RSA qu'à partir de 25 ans. Êtes-vous favorable à son ouverture dès 18 ans ?"
label variable pe11 "PE11. D'après ce que vous en savez, quel est le montant du SMIC net (par mois en euros) ?"
label variable pe12 "PE12. Avec laquelle de ces opinions sur le SMIC êtes-vous le plus d'accord ?"
label variable pe13_ab "PE13_AB. Selon vous, les allocations chômage doivent-elles être un droit limité dans le temps, que l'on trouve ou non un emploi ?"
label variable pe13_cd "PE13_CD. Selon vous, les allocations chômage doivent-elles être un droit limité dans le temps ?"
label variable pe14_1 "PE14_1. Trouveriez-vous normal qu'on demande aux personnes qui touchent des allocations chômage. d'accepter les emplois correspondant à leurs qualifications et pas trop éloignés de leur domicile ?"
label variable pe14_2 "PE14_2. Trouveriez-vous normal qu'on demande aux personnes qui touchent des allocations chômage. d'accepter les emplois quels que soient la qualification et le lieu ?"
label variable pe14_3 "PE14_3. Trouveriez-vous normal qu'on demande aux personnes qui touchent des allocations chômage. d'accepter d'effectuer un stage de formation ?"
label variable pe14_4 "PE14_4. Trouveriez-vous normal qu'on demande aux personnes qui touchent des allocations chômage. de participer à une tâche d'intérêt général ?"
label variable pe15 "PE15. Actuellement, compte tenu de votre situation globale, du montant des aides publiques et de vos impôts, vous considérez que."
label variable me3 ""
label variable lo1 "LO1. Concernant votre résidence principale, êtes-vous..."
label variable lo2 "LO2. Avez-vous un remboursement de prêt en cours pour votre résidence principale ?"
label variable re1 "RE1. À l'heure actuelle, comment évaluez-vous le niveau de vie moyen des retraités par rapport à celui de l'ensemble de la population ?"
label variable re2 "RE2. Lorsque vous serez à la retraite, comment pensez-vous que votre niveau de vie sera par rapport à celui de l'ensemble de la population ?"
label variable re3 "RE3. Compte tenu des problèmes de financement des systèmes de retraite, quelle baisse de revenu vous semble acceptable au moment du départ en retraite ?"
label variable re4 "RE4. Dans l'idéal, à quel âge souhaiteriez-vous ou auriez-vous aimé prendre votre retraite ?"
label variable re5 "RE5. À quel âge, d'après vous, pourrez-vous prendre votre retraite ?"
label variable re16 "RE16. À quel âge avez-vous pris votre retraite ?"
label variable re6 "RE6. À partir de quel âge estimez-vous qu'il n'est plus acceptable de faire travailler les gens ?"
label variable re9bis "RE9BIS. Pensez-vous que pour préserver le système de retraite par répartition tel qu'il existe."
label variable re9 "RE9. Parmi les solutions suivantes pour préserver le système de retraite par répartition tel qu'il existe, laquelle a votre préférence ?"
label variable re10 "RE10. À l'avenir, que faudrait-il faire en priorité en matière de retraite ?"
label variable fa1 "FA1. Selon vous, quel devrait être l'objectif prioritaire de la politique familiale ?"
label variable fa2 "FA2. Selon vous, quelles sont les familles qu'il faut aider en priorité ?"
label variable fa3_ab "FA3. En dehors des parents, quel vous semble être le mode de garde ou d'accueil le plus bénéfique pour un enfant en bas âge ?"
label variable fa3_cd "FA3_CD. En dehors des parents, quel mode de garde ou d'accueil vous semble le plus bénéfique pour un enfant en bas âge ?"
label variable fa4 "FA4. Quel est le mode de garde ou d'accueil que vous avez principalement utilisé pour vos enfants ?"
label variable fa5 "FA5. En ce qui concerne la garde des enfants, avec laquelle de ces deux propositions suivantes êtes-vous le plus d'accord ?"
label variable fa17 "FA17. Lorsqu'un des parents s'arrête de travailler ou réduit son temps de travail pour s'occuper de ses enfants, pensez-vous."
label variable fa6 "FA6. Aujourd'hui le congé de maternité est de 16 semaines au premier et deuxième enfant et de 26 semaines à partir du troisième, pensez-vous que ces durées sont ."
label variable fa7 "FA7. En complément du congé de 3 jours au moment de la naissance, le congé paternité permet au père d'un enfant de bénéficier de 11 jours de congé. Selon vous, faut-il..."
label variable fa8 "FA8. Faut-il rendre le congé paternité obligatoire ?"
label variable fa9_1 "FA9_1. Souhaiteriez-vous ou auriez-vous souhaité recevoir de l'aide dans l'accompagnement de votre rôle de parent... dans vos relations avec l'école ?"
label variable fa9_2 "FA9_2. Souhaiteriez-vous ou auriez-vous souhaité recevoir de l'aide dans l'accompagnement de votre rôle de parent. pour gérer l'autorité, ce qu'il faut permettre ou interdire ?"
label variable fa9_3 "FA9_3. Souhaiteriez-vous ou auriez-vous souhaité recevoir de l'aide dans l'accompagnement de votre rôle de parent. sur les questions de santé ?"
label variable fa9_4 "FA9_4. Souhaiteriez-vous ou auriez-vous souhaité recevoir de l'aide dans l'accompagnement de votre rôle de parent... en cas de conflits familiaux et/ou de rupture ?"
label variable fa9_5 "FA9_5. Souhaiteriez-vous ou auriez-vous souhaité recevoir de l'aide dans l'accompagnement de votre rôle de parent... sur l'éveil et le développement du jeune enfant ?"
label variable fa10 "FA10. En cas de séparation des parents, quelle solution vous semble la plus satisfaisante pour la garde des enfants ?"
label variable fa18 "FA18. Après un divorce ou une séparation, lorsqu'il a été décidé qu'un des parents doit verser une pension alimentaire pour les enfants à l'autre parent. Pensez-vous."
label variable fa11 "FA11. Actuellement, les allocations familiales sont versées aux familles d'au moins deux enfants. Avec laquelle de ces propositions êtes-vous le plus d'accord ?"
label variable fa12 "FA12. Actuellement, le montant des allocations familiales augmente avec le rang de l'enfant. Avec laquelle de ces propositions êtes-vous le plus d'accord ?"
label variable fa13 "FA13. Actuellement, le montant des allocations familiales dépend des ressources des familles. Selon-vous, il faut."
label variable fa14 "FA14. Êtes-vous favorables à ce que les couples homosexuels puissent adopter un enfant ?"
label variable fa15 "FA15. Êtes-vous favorables à ce que les couples de femmes puissent recourir à la procréation médicalement assistée pour avoir un enfant ?"
label variable fa16 "FA16. Êtes-vous favorable à ce que les couples hétérosexuels et/ou les couples homosexuels puissent recourir à la gestation pour autrui pour avoir un enfant ?"
label variable ha1 "HA1. À votre avis, la société actuelle se donne-t-elle les moyens d'intégrer les personnes handicapées ?"
label variable de1 "DE1. Selon vous, qui doit principalement prendre en charge financièrement les personnes âgées dépendantes ?"
label variable de4 "DE4. Seriez-vous prêt.e à épargner davantage en prévision d'une éventuelle situation de dépendance vous concernant ?"
label variable de5 "DE5. Si l'un de vos parents proches devenait dépendant, que feriez-vous ?"
label variable de7 "DE7. Vous personnellement, apportez-vous une aide régulière et bénévole à une personne âgée dépendante vivant chez vous, chez elle ou ailleurs (institution.) ?"
label variable ps1_1 "PS1_1. À votre avis, l'assurance maladie devrait-elle bénéficier..."
label variable ps1_2 "PS1_2. À votre avis, les retraites devraient-elles bénéficier."
label variable ps1_3 "PS1_3. À votre avis, les allocations familiales devraient-elles bénéficier..."
label variable ps1_4 "PS1_4. À votre avis les allocations chômage devraient-elles bénéficier..."
label variable ps2 "PS2. Actuellement, les entreprises cotisent pour la protection sociale. Avec laquelle des trois propositions suivantes, êtes-vous le plus d'accord ? À l'avenir..."
label variable ps3 "PS3. La France consacre environ le tiers du revenu national au financement de la protection sociale. Considérez-vous que c'est."
label variable ps13_1 "PS13_1. Accepteriez-vous une baisse de l'assurance maladie en échange d'une baisse de vos impôts ou de vos cotisations ?"
label variable ps13_2 "PS13_2. Accepteriez-vous une baisse des retraites en échange d'une baisse de vos impôts ou de vos cotisations ?"
label variable ps13_3 "PS13_3. Accepteriez-vous une baisse des allocations familiales en échange d'une baisse de vos impôts ou de vos cotisations ?"
label variable ps13_4 "PS13_4. Accepteriez-vous une baisse des allocations chômage en échange d'une baisse de vos impôts ou de vos cotisations ?"
label variable ps13_5 "PS13_5. Accepteriez-vous une baisse des aides aux personnes handicapées en échange d'une baisse de vos impôts ou de vos cotisations ?"
label variable ps13_6 "PS13_6. Accepteriez-vous une baisse des aides aux personnes âgées dépendantes en échange d'une baisse de vos impôts ou de vos cotisations ?"
label variable ps13_7 "PS13_7. Accepteriez-vous une baisse des allocations logement en échange d'une baisse de vos impôts ou de vos cotisations ?"
label variable ps15_1 "PS15_1. « Notre système de sécurité sociale... fournit un niveau de protection suffisant »"
label variable ps15_2 "PS15_2. « Notre système de sécurité sociale... peut servir de modèle à d'autres pays »"
label variable ps15_3 "PS15_3. « Notre système de sécurité sociale... coûte trop cher à la société »"
label variable ps18 "PS18. En matière de politique sociale, quel type d'actions vous semble le plus nécessaire aujourd'hui ?"
label variable sa1 "SA1. Comment est votre état de santé général ?"
label variable sa3 "SA3. Êtes-vous limité.e depuis au moins 6 mois à cause d'un problème de santé, dans les activités que les gens font habituellement ?"
label variable sa4 "SA4. Avez-vous une affection de longue durée, appelée aussi ALD, pour laquelle vos soins sont pris en charge à 100 % par l'Assurance maladie ou la Sécurité sociale ?"
label variable sa5 "SA5. Selon vous, au cours des dernières années, l'état de santé des Français s'est."
label variable sa6_ab_1 "SA6_AB_1. « En France, tout le monde peut être soigné quel que soit son revenu »"
label variable sa6_ab_2 "SA6_AB_2. « En France, on a la même qualité de soins quel que soit son revenu »"
label variable sa6_ab_3 "SA6_AB_3. « En France, tout le monde peut être soigné quel que soit le lieu où il habite »"
label variable sa6_ab_4 "SA6_AB_4. « En France, on a la même qualité de soins quel que soit le lieu où l'on habite »"
label variable sa6_ab_5 "SA6_AB_5. « En France, les délais d'attente pour se faire soigner ne dépendent pas du revenu »"
label variable sa6_ab_6 "SA6_AB_6. « En France, les délais d'attente pour se faire soigner ne dépendent pas du lieu où l'on habite »"
label variable sa6_cd_1 "SA6_CD_1. « En France, tout le monde peut être soigné quel que soit son revenu »"
label variable sa6_cd_2 "SA6_CD_2. « En France, on a la même qualité de soins quel que soit son revenu »"
label variable sa6_cd_3 "SA6_CD_3. « En France, tout le monde peut être soigné quel que soit le lieu où il habite »"
label variable sa6_cd_4 "SA6_CD_4. « En France, on a la même qualité de soins quel que soit le lieu où l'on habite »"
label variable sa6_cd_5 "SA6_CD_5. « En France, on a les mêmes délais d'attente pour se faire soigner quel que soit son revenu »"
label variable sa6_cd_6 "SA6_CD_6. « En France, on a les mêmes délais d'attente pour se faire soigner quel que soit le lieu où l'on habite »"
label variable me4 "ME4. Êtes-vous inquiets à l'idée de ne pas pouvoir être bien soigné en cas de gros problème de santé ?"
label variable sa7_1 "SA7_1. En général, êtes-vous satisfait de la qualité des soins offerts par les . hôpitaux publics (hors services d'urgence et maternités) ?"
label variable sa7_2 "SA7_2. En général, êtes-vous satisfait de la qualité des soins offerts par les . urgences hospitalières ?"
label variable sa7_3 "SA7_3. En général, êtes-vous satisfait de la qualité des soins offerts par les . cliniques privées ?"
label variable sa7_4 "SA7_4. En général, êtes-vous satisfait de la qualité des soins offerts par les . dentistes, orthodontistes ?"
label variable sa7_5 "SA7_5. En général, êtes-vous satisfait de la qualité des soins offerts par les . médecins généralistes (hors hôpital) ?"
label variable sa7_6 "SA7_6. En général, êtes-vous satisfait de la qualité des soins offerts par les . médecins spécialistes (hors hôpital) ?"
label variable sa7_7 "SA7_7. En général, êtes-vous satisfait de la qualité des soins offerts par les . infirmiers/infirmières (hors hôpital) ?"
label variable sa7_8 "SA7_8. En général, êtes-vous satisfait de la qualité des soins offerts par les . maternités ?"
label variable sa8_1 "SA8_1. Pour réduire le déficit de la branche maladie de la Sécurité sociale, seriez-vous plutôt favorable ou opposé.e à. augmenter les cotisations ?"
label variable sa8_2 "SA8_2. Pour réduire le déficit de la branche maladie de la Sécurité sociale, seriez-vous plutôt favorable ou opposé.e à. limiter le remboursement de la Sécurité sociale pour certaines prestations  ?"
label variable sa8_3 "SA8_3. Pour réduire le déficit de la branche maladie de la Sécurité sociale, seriez-vous plutôt favorable ou opposé.e à. réduire la prise en charge des longues maladies par la sécurité sociale ?"
label variable sa8_5 "SA8_5. Pour réduire le déficit de la branche maladie de la Sécurité sociale, seriez-vous plutôt favorable ou opposé.e à. modifier les habitudes des médecins pour qu'ils prescrivent moins de médicaments et d'examens ?"
label variable sa8_6 "SA8_6. Pour réduire le déficit de la branche maladie de la Sécurité sociale, seriez-vous plutôt favorable ou opposé.e à. limiter les tarifs des professionnels de santé ?"
label variable sa8_7 "SA8_7. Pour réduire le déficit de la branche maladie de la Sécurité sociale, seriez-vous plutôt favorable ou opposé.e à. taxer davantage les fabricants de médicaments ?"
label variable sa8_9 "SA8_9. Pour réduire le déficit de la branche maladie de la Sécurité sociale, seriez-vous plutôt favorable ou opposé.e à. permettre aux infirmiers / pharmaciens de faire certaines tâches à la place des médecins ?"
label variable sa9_1 "SA9_1. À votre avis, pensez-vous qu'il y a à proximité de chez vous des... médecins généralistes ?"
label variable sa9_2 "SA9_2. À votre avis, pensez-vous qu'il y a à proximité de chez vous des. médecins spécialistes ?"
label variable sa9_3 "SA9_3. À votre avis, pensez-vous qu'il y a à proximité de chez vous des... infirmiers / infirmières ?"
label variable sa9_4 "SA9_4. À votre avis, pensez-vous qu'il y a à proximité de chez vous des... kinésithérapeutes ?"
label variable sa9_5 "SA9_5. À votre avis, pensez-vous qu'il y a à proximité de chez vous des. dentistes ?"
label variable sa9_6 "SA9_6. À votre avis, pensez-vous qu'il y a à proximité de chez vous des. pharmaciens ?"
label variable sa22_1 "SA22_1. Avez-vous, au cours de ces dernières années, fait appel à un hôpital public (hors services urgences et maternités) pour vous ou pour vos proches ?"
label variable sa22_2 "SA22_2. Avez-vous, au cours de ces dernières années, fait appel aux urgences hospitalières pour vous ou pour vos proches ?"
label variable sa22_3 "SA22_3. Avez-vous, au cours de ces dernières années, fait appel à une clinique privée pour vous ou pour vos proches ?"
label variable sa22_4 "SA22_4. Avez-vous, au cours de ces dernières années, fait appel à un dentiste / orthodontiste pour vous ou pour vos proches ?"
label variable sa22_5 "SA22_5. Avez-vous, au cours de ces dernières années, fait appel à un médecin généraliste pour vous ou pour vos proches ?"
label variable sa22_6 "SA22_6. Avez-vous, au cours de ces dernières années, fait appel à un médecin spécialiste (hors hôpital) pour vous ou pour vos proches ?"
label variable sa22_7 "SA22_7. Avez-vous, au cours de ces dernières années, fait appel à un infirmier / une infirmière (hors hôpital)  pour vous ou pour vos proches ?"
label variable sa22_8 "SA22_8. Avez-vous, au cours de ces dernières années, fait appel à une maternité pour vous ou pour vos proches ?"
label variable sa26_1 "SA26_1. De quand date votre dernière visite chez le médecin généraliste (hors hôpital) ?"
label variable sa26_2 "SA26_2. De quand date votre dernière visite chez un médecin spécialiste (hors hôpital) ?"
label variable cs1 "CS1. Selon vous, la cohésion sociale en France est-elle actuellement."
label variable cs24 "CS24. Selon vous, comment la solidarité entre les générations a-t-elle évolué au cours des dix dernières années ?"
label variable cs4 "CS4. Auquel de ces lieux avez-vous personnellement le sentiment d'appartenir avant tout ?"
label variable cs5_ab "CS5_AB. Avez-vous le sentiment d'être intégré.e dans la société française ?"
label variable cs5_cd "CS5_CD. Avez-vous le sentiment d'être intégré.e dans la société ?"
label variable cs17 "CS17. Selon vous, les pouvoirs publics devraient-ils ou non renforcer leur action pour soutenir l'intégration des personnes étrangères dans notre société ?"
label variable cs18 "CS18. Estimez-vous que les pouvoirs publics font trop, font ce qu'ils doivent ou ne font pas assez pour les plus démunis ?"
label variable cs19_1 "CS19_1. «  Beaucoup de personnes ne bénéficient pas des droits ou allocations auxquels elles peuvent prétendre  »"
label variable cs19_2 "CS19_2. «  Beaucoup de personnes perçoivent des allocations alors qu'elles n'y ont pas droit »"
label variable cs20 "CS20. Pour quelle raison principale pensez-vous que certaines personnes ne bénéficient pas d'allocations, droits, aides ou tarifs sociaux auxquels elles peuvent prétendre ?"
label variable cs13 "CS13. Pour vous, les pouvoirs publics doivent-ils en priorité."
label variable cs14 "CS14. Quelle opinion se rapproche le plus de la vôtre ?"
label variable cs9 "CS9. Au cours des 12 derniers mois, avez-vous été témoin de discriminations liées au fait d'être une femme ?"
label variable cs21_1 "CS21_1. Vous sentez-vous particulièrement proche... de ceux qui sont de la même génération que vous ?"
label variable cs21_2 "CS21_2. Vous sentez-vous particulièrement proche... de ceux qui partagent la même situation socio-économique que vous ?"
label variable cs21_3 "CS21_3. Vous sentez-vous particulièrement proche... de ceux qui partagent les mêmes convictions politiques que vous ?"
label variable cs21_4 "CS21_4. Vous sentez-vous particulièrement proche... de ceux qui habitent dans le même quartier/village que vous ?"
label variable cs21_5 "CS21_5. Vous sentez-vous particulièrement proche... de ceux qui ont la même religion que vous ?"
label variable cs21_6 "CS21_6. Vous sentez-vous particulièrement proche... de ceux qui ont les mêmes origines que vous ?"
label variable cs21_7 "CS21_7. Vous sentez-vous particulièrement proche... des autres femmes.hommes ?"
label variable cs22 "CS22. Selon vous, entre quels types de groupes les tensions seront-elles les plus fortes à l'avenir ?"
label variable cs23 "CS23. Pensez-vous que la France devrait accueillir moins d'un migrant sur huit, à peu près ce chiffre ou davantage ?"
label variable sdassynd_1 "SDASSYND_1. Vous personnellement, êtes-vous membre d'une organisation syndicale ?"
label variable sdassynd_2 "SDASSYND_2. Vous personnellement, êtes-vous membre d'une association ?"
label variable sdrel "SDREL. Vis-à-vis de la religion, avez-vous."
label variable sdproxim_1 "SDPROXIM_1. Dans votre famille ou en dehors de votre famille, connaissez-vous quelqu'un au chômage, indemnisé.e ?"
label variable sdproxim_2 "SDPROXIM_2. Dans votre famille ou en dehors de votre famille, connaissez-vous quelqu'un au chômage, non indemnisé.e ?"
label variable sdproxim_3 "SDPROXIM_3. Dans votre famille ou en dehors de votre famille, connaissez-vous quelqu'un qui est SDF ?"
label variable sdproxim_4 "SDPROXIM_4. Dans votre famille ou en dehors de votre famille, connaissez-vous quelqu'un élevant seul.e ses enfants avec un revenu inférieur au SMIC ?"
label variable sdproxim_5 "SDPROXIM_5. Dans votre famille ou en dehors de votre famille, connaissez-vous quelqu'un pensionné.e (invalide / handicapé.e) sans pouvoir travailler ?"
label variable sdproxim_6 "SDPROXIM_6. Dans votre famille ou en dehors de votre famille, connaissez-vous quelqu'un occupant un emploi précaire ?"
label variable sdproxim_7 "SDPROXIM_7. Dans votre famille ou en dehors de votre famille, connaissez-vous quelqu'un au RSA ?"
label variable sdproxim_8 "SDPROXIM_8. Dans votre famille ou en dehors de votre famille, connaissez-vous une personne handicapée de moins de 60 ans ?"
label variable sdproxim_9 "SDPROXIM_9. Dans votre famille ou en dehors de votre famille, connaissez-vous une personne âgée dépendante ?"
label variable sdrichom_ab "SDRICHOM_AB.Y a-t-il un risque de chômage dans les mois à venir pour vous-même ou l'un de vos proches ?"
label variable sdrichom_cd_1 "SDRICHOM_1_CD. Y a-t-il un risque de chômage dans les mois à venir pour vous-même ?"
label variable sdrichom_cd_2 "SDRICHOM_2_CD. Y a-t-il un risque de chômage dans les mois à venir pour l'un de vos proches ?"
label variable sdres_1 "SDRES_1. Au cours des douze derniers mois, votre ménage a-t-il perçu des ressources provenant de salaires, traitements et primes ?"
label variable sdres_2 "SDRES_2. Au cours des douze derniers mois, votre ménage a-t-il perçu des ressources provenant de revenus d'une activité professionnelle indépendante ?"
label variable sdres_3 "SDRES_3. Au cours des douze derniers mois, votre ménage a-t-il perçu des ressources provenant du RSA (Revenu de solidarité active) ?"
label variable sdres_4 "SDRES_4. Au cours des douze derniers mois, votre ménage a-t-il perçu des ressources provenant des allocations de chômage ?"
label variable sdres_5 "SDRES_5. Au cours des douze derniers mois, votre ménage a-t-il perçu des ressources provenant de préretraite, retraites ?"
label variable sdres_6 "SDRES_6. Au cours des douze derniers mois, votre ménage a-t-il perçu des ressources provenant de revenus d'actifs financiers ?"
label variable sdres_7 "SDRES_7. Au cours des douze derniers mois, votre ménage a-t-il perçu des ressources provenant de revenus de locations ?"
label variable sdres_8 "SDRES_8. Au cours des douze derniers mois, votre ménage a-t-il perçu des ressources provenant de prestations familiales ?"
label variable sdres_9 "SDRES_9. Au cours des douze derniers mois, votre ménage a-t-il perçu des ressources provenant des allocations de logement ?"
label variable sdres_10 "SDRES_10. Au cours des douze derniers mois, votre ménage a-t-il perçu des ressources provenant de prestations liées au handicap, à l'invalidité ou à la dépendance ?"
label variable sdres_11 "SDRES_11. Au cours des douze derniers mois, votre ménage a-t-il perçu des ressources provenant de bourses d'études ?"
label variable sdres_12 "SDRES_12. Au cours des douze derniers mois, votre ménage a-t-il perçu des ressources provenant de pensions alimentaires ou argent reçu tous les mois de la part de proches ?"
label variable sdrevcl "SDREVCL. Revenus mensuels nets avant impôts du foyer"
label variable sdrevtr "SDREVTR. Revenus mensuels nets avant impôts du foyer (en tranches)"
label variable me5 "ME5. Globalement, diriez-vous que les revenus de votre foyer sont plutôt variables ou plutôt stables d'un mois sur l'autre ?"
label variable me6 "ME6. Dans les mois qui viennent, pensez-vous que les revenus de votre foyer vont."
label variable sddipl "SDDIPL. Niveau de diplôme"
label variable sdpol "SDPOL. Sur une échelle de 0 à 10, où vous classeriez-vous politiquement ?"
label variable sdpoltr "SDPOLTR. Sur une échelle de 0 à 10, où vous classeriez-vous politiquement ? (en 5 tranches)"
label variable sdnat "SDNAT. Nationalité"
label variable sdpnaistr "SDPNAISTR. Quel est votre pays de naissance ?"
label variable sdanfrtr "SDANFR. Vous êtes né.e à l'étranger, en quelle année êtes-vous arrivé en France ?"
label variable sdnatp "SDNATP. Quelle était la nationalité de votre père à sa naissance ?"
label variable sdpnaisptr "SDPNAISPTR. Quel est le pays de naissance de votre père ?"
label variable sdnatm "SDNATM. Quelle était la nationalité de votre mère à sa naissance ?"
label variable sdpnaismtr "SDPNAISMTR. Quel est le pays de naissance de votre mère ?"
label variable sdrevcl_imput "SDREVCL_IMPUT. Revenus mensuels nets du ménage imputé"
label variable sdniviecl_imput "SDNIVIECL_IMPUT. Niveau de vie mensuel du ménage imputé"
label variable sdnivie "SDNIVIE. Quintile de niveau de vie du ménage (imputé)"
label variable sdageenftr_1 "SDAGEENFTR_1. Nombre d'enfants de 0 à 3 ans"
label variable sdageenftr_2 "SDAGEENFTR_2. Nombre d'enfants de 4 à 6 ans"
label variable sdageenftr_3 "SDAGEENFTR_3. Nombre d'enfants de 7 à 13 ans"
label variable sdageenftr_4 "SDAGEENFTR_4. Nombre d'enfants de 14 à 17 ans"
label variable sdageenftr_5 "SDAGEENFTR_5. Nombre d'enfants de 18 ans ou plus"
