label variable ident "IDENT. Identifiant unique"
label variable annee "ANNEE. Année"
label variable poids "POIDS. Poids de redressement"
label variable sdnbadu "SDNBADU. Nombre d'adultes vivant au foyer"
label variable sdsplit "SDSPLIT. Version du questionnaire"
label variable sdreg "REGION. ZEAT"
label variable habitat "HABITAT. Catégorie d'agglomération"
label variable sdsexe "SDSEXE. Sexe de l’enquêté.e"
label variable sdage "SDAGE. Âge"
label variable sdagetr "SDAGETR. Âge (en tranches)"
label variable sdsitua "SDSITUA. Quelle est votre situation actuellement ?"
label variable co1 "CO1. Votre situation professionnelle a-t-elle changé en lien avec la crise du Covid ?"
label variable sdact "SDACT. Activité principale de l’interviewé.e (ou ancienne activité)"
label variable sdstat "SDSTAT. Statut d'activité de l'interviewé.e"
label variable sdpcs7 "SDPCS7. Profession de l’interviewé.e (ou ancienne profession) en 7 catégories"
label variable sdpcs10 "SDPCS10. Profession actuelle de l’interviewé.e en 10 catégories"
label variable sdstatemp "SDSTATEMP. Type de contrat (ou ancien type de contrat)"
label variable sdsitfam "SDSITFAM. Quelle est votre situation familiale dans le foyer ?"
label variable sdpr "SDPR. Désignation de la personne de référence"
label variable sdprsitua "SDPRSITUA. Situation de la personne de référence"
label variable sdpract "SDPRACT. Activité principale de la personne de référence (ou ancienne activité principale)"
label variable sdprstat "SDPRSTAT. Statut d'activité de la personne de référence"
label variable sdprpcs7 "SDPRPCS7. Profession de la personne de référence (ou ancienne profession) en 7 catégories"
label variable sdprpcs10 "SDPRPCS10. Profession  actuelle de la personne de référence en 10 catégories"
label variable sdnbpers "SDNBPERS. Nombre de personnes dans le foyer"
label variable sdcouple "SDCOUPLE. Vivez-vous en couple ?"
label variable sdmatri "SDMATRI. Statut marital"
label variable sdmatri_det "SDMATRI_DET. Statut marital détaillé"
label variable sdnbenf "SDNBENF. Combien y-a-t-il d'enfants à charge dans votre foyer ?"
label variable sdageenf_1 "SDAGEENF_1. Âge du 1er enfant"
label variable sdageenf_2 "SDAGEENF_2. Âge du 2ème enfant"
label variable sdageenf_3 "SDAGEENF_3. Âge du 3ème enfant"
label variable sdageenf_4 "SDAGEENF_4. Âge du 4ème enfant"
label variable sdageenf_5 "SDAGEENF_5. Âge du 5ème enfant"
label variable sdageenf_6 "SDAGEENF_6. Âge du 6ème enfant"
label variable sdageenf_7 "SDAGEENF_7. Âge du 7ème enfant"
label variable sdageenf_8 "SDAGEENF_8. Âge du 8ème enfant"
label variable sdageenf_9 "SDAGEENF_9. Âge du 9ème enfant"
label variable sdageenf_10 "SDAGEENF_10. Âge du 10ème enfant"
label variable sduc "SDUC. Nombre d'unités de consommation du ménage"
label variable sdmut "SDMUT. Êtes-vous couvert.e par une mutuelle ou une assurance complémentaire maladie ?"
label variable og1_ab "OG1_AB. Vous personnellement, comment qualifieriez-vous votre situation actuelle ?"
label variable og1_cd "OG1_CD. Vous personnellement, comment qualifieriez-vous votre situation actuelle DEPUIS LA CRISE DU COVID ? Diriez-vous de votre situation actuelle, qu’elle est  ..."
label variable og2 "OG2. Par rapport à la situation de vos parents au même âge, diriez-vous que votre situation actuelle est…"
label variable og3_1 "OG3_1. Quand vous pensez à l'avenir, êtes-vous plutôt optimiste ou plutôt pessimiste... pour vous-même ?"
label variable og3_2 "OG3_2. Quand vous pensez à l'avenir, êtes-vous plutôt optimiste ou plutôt pessimiste... pour vos enfants ou les générations futures ?"
label variable og4_1 "OG4_1. Êtes-vous personnellement préoccupé(e) par… le logement ?"
label variable og4_3 "OG4_3. Êtes-vous personnellement préoccupé(e) par… la pauvreté ?"
label variable og4_4 "OG4_4. Êtes-vous personnellement  préoccupé(e) par… l'insécurité dans votre quartier ou votre village ?"
label variable og4_5 "OG4_5. Êtes-vous personnellement préoccupé(e) par… la dette de la France ?"
label variable og4_6 "OG4_6. Êtes-vous personnellement  préoccupé(e) par… le chômage ?"
label variable og4_7 "OG4_7. Êtes-vous personnellement  préoccupé(e) par… les crises financières internationales ?"
label variable og4_8 "OG4_8. Êtes-vous personnellement préoccupé(e) par… la santé des Français ?"
label variable og4_9 "OG4_9. Êtes-vous personnellement  préoccupé(e) par… le niveau des salaires et du pouvoir d'achat ?"
label variable og5_1 "OG5_1. Êtes-vous personnellement préoccupé(e) par… les problèmes liés à l’environnement ?"
label variable og5_4 "OG5_4.Êtes-vous personnellement préoccupé(e) par… l'avenir du système de retraite ?"
label variable og5_5 "OG5_5. Êtes-vous personnellement  préoccupé(e) par… le cancer ?"
label variable og5_6 "OG5_6. Êtes-vous personnellement préoccupé(e) par… les risques d'épidémie ?"
label variable og5_7 "OG5_7. Êtes-vous personnellement préoccupé(e) par… les inégalités entre les femmes et les hommes ?"
label variable og7_ab "OG7_AB. Pensez-vous qu'il y a trop d'intervention de l'État en matière économique et sociale, juste ce qu'il faut ou pas assez ?"
label variable og7_cd "OG7_CD. Pensez-vous qu’il y a trop d’intervention de l’État en matière économique et sociale DEPUIS LA CRISE DU COVID, juste ce qu’il faut ou pas assez ?"
label variable og8_1 "OG8_1. « Il y a trop de travailleurs immigrés »"
label variable og8_2 "OG8_2. « Les filles ont autant l’esprit scientifique que les garçons »"
label variable og8_3 "OG8_3. « Les couples homosexuels peuvent assumer un rôle de parent comme les couples hétérosexuels »"
label variable og8_4 "OG8_4. « Les femmes font de meilleures infirmières que les hommes »"
label variable og8_6 "OG8_6. « Aujourd'hui, on se marie, on se quitte, on forme un autre foyer et les enfants s'y adaptent très bien »"
label variable og8_8 "OG8_8. « Les mères savent mieux répondre aux besoins et attentes des enfants que les pères »"
label variable og8_9 "OG8_9. « Dans l'idéal, les femmes devraient rester à la maison pour élever leurs enfants »"
label variable og8_11 "OG8_11. « Les hommes sont de meilleurs managers d’équipe au sein d’une entreprise que les femmes »"
label variable og9 "OG9. Selon vous, qu'est-ce qui est le plus important pour réussir dans la vie à l'heure actuelle en France ?"
label variable og10_ab "OG10_AB. Chez vous, les courses, le ménage et le linge sont-ils faits…"
label variable og10_cd "OG10_CD. Chez vous, DURANT LE CONFINEMENT, les courses, le ménage et le linge ont-ils été faits :"
label variable og12 "OG12. Toujours concernant la répartition des tâches ménagères, pensez-vous qu'aujourd'hui, par rapport à il y a 20 ans…"
label variable og13_1 "OG13_1. Avez-vous entendu parler… Du revenu de solidarité active ou RSA"
label variable og13bis_1 "OG13bis_1. Savez-vous qui peut bénéficier… Du revenu de solidarité active ou RSA"
label variable og13ter_1 "OG13ter_1. Avez-vous entendu parler et savez-vous qui peut bénéficier… Du revenu de solidarité active ou RSA"
label variable og13_2 "OG13_2. Avez-vous entendu parler… Des allocations familiales"
label variable og13bis_2 "OG13bis_2. Savez-vous qui peut bénéficier … Des allocations familiales"
label variable og13ter_2 "OG13ter_2. Avez-vous entendu parler et savez-vous qui peut bénéficier… Des allocations familiales"
label variable og13_3 "OG13_3. Avez-vous entendu parler… De l’allocation personnalisée d’autonomie ou APA"
label variable og13bis_3 "OG13bis_3. Savez-vous qui peut bénéficier … De l’allocation personnalisée d’autonomie ou APA"
label variable og13ter_3 "OG13ter_3. Avez-vous entendu parler et savez-vous qui peut bénéficier… De l’allocation personnalisée d’autonomie ou APA"
label variable og13_4 "OG13_4. Avez-vous entendu parler… De la complémentaire santé solidaire sans participation financière (ex CMU-C) ou CSS gratuite"
label variable og13bis_4 "OG13bis_4. Savez-vous qui peut bénéficier … De la complémentaire santé solidaire sans participation financière (ex CMU-C) ou CSS gratuite"
label variable og13ter_4 "OG13ter_4. Avez-vous entendu parler et savez-vous qui peut bénéficier… De la complémentaire santé solidaire sans participation financière (ex CMU-C) ou CSS gratuite"
label variable og13_5 "OG13_5. Avez-vous entendu parler… De l’allocation pour les adultes handicapés ou AAH"
label variable og13bis_5 "OG13bis_5. Savez-vous qui peut bénéficier … De l’allocation pour les adultes handicapés ou AAH"
label variable og13ter_5 "OG13ter_5. Avez-vous entendu parler et savez-vous qui peut bénéficier… De l’allocation pour les adultes handicapés ou AAH"
label variable og13_6 "OG13_6. Avez-vous entendu parler… Du minimum vieillesse ou allocation de solidarité aux personnes âgées (ASPA)"
label variable og13bis_6 "OG13bis_6. Savez-vous qui peut bénéficier … Du minimum vieillesse ou allocation de solidarité aux personnes âgées (ASPA)"
label variable og13ter_6 "OG13ter_6. Avez-vous entendu parler et savez-vous qui peut bénéficier… Du minimum vieillesse ou allocation de solidarité aux personnes âgées (ASPA)"
label variable og13_7 "OG13_7. Avez-vous entendu parler… Des aides au logement"
label variable og13bis_7 "OG13bis_7. Savez-vous qui peut bénéficier … Des aides au logement"
label variable og13ter_7 "OG13ter_7. Avez-vous entendu parler et savez-vous qui peut bénéficier… Des aides au logement"
label variable og13_8 "OG13_8. Avez-vous entendu parler… De la prime d’activité ou PA"
label variable og13bis_8 "OG13bis_8. Savez-vous qui peut bénéficier … De la prime d’activité ou PA"
label variable og13ter_8 "OG13ter_8. Avez-vous entendu parler et savez-vous qui peut bénéficier… De la prime d’activité ou PA"
label variable og13_9 "OG13_9. Avez-vous entendu parler… De la complémentaire santé solidaire avec participation financière (ex ACS) ou CSS payante"
label variable og13bis_9 "OG13bis_9. Savez-vous qui peut bénéficier … De la complémentaire santé solidaire avec participation financière (ex ACS) ou CSS payante"
label variable og13ter_9 "OG13ter_9. Avez-vous entendu parler et savez-vous qui peut bénéficier… De la complémentaire santé solidaire avec participation financière (ex ACS) ou CSS payante"
label variable og13_10 "OG13_10. Avez-vous entendu parler… De l’allocation versée à des personnes victimes d’isolement social, ou ALIS"
label variable og13bis_10 "OG13bis_10. Savez-vous qui peut bénéficier … De l’allocation versée à des personnes victimes d’isolement social, ou ALIS"
label variable og13ter_10 "OG13ter_10. Avez-vous entendu parler et savez-vous qui peut bénéficier… De l’allocation versée à des personnes victimes d’isolement social, ou ALIS"
label variable og13_11 "OG13_11. Avez-vous entendu parler… De l’aide médicale d’État ou AME"
label variable og13bis_11 "OG13bis_11. Savez-vous qui peut bénéficier … De l’aide médicale d’État ou AME"
label variable og13ter_11 "OG13ter_11. Avez-vous entendu parler et savez-vous qui peut bénéficier… De l’aide médicale d’État ou AME"
label variable og13_12 "OG13_12. Avez-vous entendu parler… Du 100 % santé appelé aussi « Panier 100 % santé » ou encore « Reste à charge zéro »"
label variable og13bis_12 "OG13bis_12. Savez-vous qui peut bénéficier … Du 100 % santé appelé aussi « Panier 100 % santé » ou encore « Reste à charge zéro »"
label variable og13ter_12 "OG13ter_12. Avez-vous entendu parler et savez-vous qui peut bénéficier… Du 100 % santé appelé aussi « Panier 100 % santé » ou encore « Reste à charge zéro »"
label variable in1_ab "IN1_AB. La société française aujourd'hui, vous paraît-elle plutôt juste ou plutôt injuste ?"
label variable in1_cd "IN1_CD. DEPUIS LA CRISE DU COVID, la société française vous paraît-elle plutôt juste ou plutôt injuste ?"
label variable in2 "IN2. Globalement, depuis 5 ans, diriez-vous que les inégalités en France…"
label variable in3 "IN3. À l'avenir, pensez-vous que les inégalités en France…"
label variable in4 "IN4. Quel type d’inégalité vous semble la plus répandue aujourd’hui ?"
label variable in5 "IN5. Quel type d’inégalité vous semble la moins acceptable ?"
label variable in6 "IN6. Avez-vous le sentiment que les inégalités entre les hommes et les femmes en France sont aujourd'hui..."
label variable in7 "IN7. Depuis 10 ans, diriez-vous que les inégalités entre les hommes et les femmes ont plutôt augmenté ou plutôt diminué en France ?"
label variable in8 "IN8. Où vous placeriez-vous aujourd’hui sur cette échelle de revenus, en comparant les revenus de votre foyer avec ceux de tous les autres foyers ?"
label variable in9 "IN9. Où placeriez-vous la famille dans laquelle vous avez grandi ?"
label variable in10_1 "IN10_1. À votre avis, que gagne (rémunération nette mensuelle) en moyenne… un ouvrier non qualifié en usine ?"
label variable in10_2 "IN10_2. À votre avis, que devrait gagner (rémunération nette mensuelle) en moyenne… un ouvrier non qualifié en usine ?"
label variable in10_3 "IN10_3. À votre avis, que gagne (rémunération nette mensuelle) en moyenne… un médecin généraliste ?"
label variable in10_4 "IN10_4. À votre avis, que devrait gagner (rémunération nette mensuelle) en moyenne… un médecin généraliste ?"
label variable in10_5 "IN10_5. À votre avis, que gagne (rémunération nette mensuelle) en moyenne… le PDG d’une grande société française ?"
label variable in10_6 "IN10_6. À votre avis, que devrait gagner (rémunération nette mensuelle) en moyenne… le PDG d'une grande société française ?"
label variable in10_7 "IN10_7. À votre avis, que gagne (rémunération nette mensuelle) en moyenne… un enseignant en école primaire ?"
label variable in10_8 "IN10_8. À votre avis, que devrait gagner (rémunération nette mensuelle) en moyenne… un enseignant en école primaire ?"
label variable in10_9 "IN10_9. À votre avis, que gagne (rémunération nette mensuelle) en moyenne… un.e infirmier.e ?"
label variable in10_10 "IN10_10. À votre avis, que devrait gagner (rémunération nette mensuelle) en moyenne… un.e infirmier.e ?"
label variable in11_1 "IN11_1. Que gagnent en moyenne les gens qui ont la même profession que vous ?"
label variable in11_2 "IN11_2. Que devraient gagner en moyenne les gens qui ont la même profession que vous ?"
label variable in12 "IN12. À partir de quel revenu mensuel diriez-vous d'une personne vivant seule qu'elle est riche ?"
label variable in13 "IN13. À partir de quel montant de patrimoine (financier et immobilier) diriez-vous d'une personne vivant seule qu'elle est riche ?"
label variable in14_1 "IN14_1. Pensez-vous qu’actuellement il faut... augmenter les impôts payés par les personnes dont le revenu est supérieur à 2500 euros par mois ?"
label variable in14_2 "IN14_2. Pensez-vous qu’actuellement il faut... interdire les rémunérations dépassant 10 000 euros par mois ?"
label variable in14_3 "IN14_3. Pensez-vous qu’actuellement il faut… réglementer les écarts de salaires dans les entreprises, pour que le salaire le plus haut ne dépasse pas dix fois le montant du salaire le plus bas ?"
label variable pe1_ab "PE1_AB. Selon vous, depuis 5 ans, la pauvreté et l'exclusion en France..."
label variable pe1_cd "PE1_CD. Selon vous, DEPUIS LA CRISE DU COVID, la pauvreté et l’exclusion en France..."
label variable pe2 "PE2. À l'avenir, pensez-vous que la pauvreté et l'exclusion en France…"
label variable pe3 "PE3. Vous personnellement, pensez-vous qu'il y a un risque que vous deveniez pauvre dans les cinq prochaines années ?"
label variable pe4_ab_1 "PE4_AB_1. Selon vous, les 18-29 ans ont-ils un risque de pauvreté plus ou moins important que la moyenne des Français ?"
label variable pe4_cd_1 "PE4_CD_1. Selon vous, DEPUIS LA CRISE DU COVID, les personnes de 18 à 29 ans ont-elles un risque de pauvreté plus ou moins important que la moyenne des Français ?"
label variable pe6_ab_1 "PE6_AB_1. Si des personnes se trouvent en situation d’exclusion ou de pauvreté, c’est parce qu’… elles ne veulent pas travailler ?"
label variable pe6_ab_2 "PE6_AB_2. Si des personnes se trouvent en situation d’exclusion ou de pauvreté, c’est parce qu’… elles manquent de qualifications, de diplômes, pour trouver ou retrouver un emploi ?"
label variable pe6_ab_3 "PE6_AB_3. Si des personnes se trouvent en situation d’exclusion ou de pauvreté, c’est parce qu’… elles n'ont pas eu de chance ?"
label variable pe6_ab_4 "PE6_AB_4. Si des personnes se trouvent en situation d’exclusion ou de pauvreté, c’est parce qu’… il n'y a plus assez de travail pour tout le monde ?"
label variable pe6_cd_1 "PE6_CD_1. Si des personnes se trouvent en situation d’exclusion ou de pauvreté DEPUIS LA CRISE DU COVID, c’est parce qu’… elles ne veulent pas travailler ?"
label variable pe6_cd_2 "PE6_CD_2. Si des personnes se trouvent en situation d’exclusion ou de pauvreté DEPUIS LA CRISE DU COVID, c’est parce qu’… elles manquent de qualifications, de diplômes, pour trouver ou retrouver un emploi ?"
label variable pe6_cd_3 "PE6_CD_3. Si des personnes se trouvent en situation d’exclusion ou de pauvreté DEPUIS LA CRISE DU COVID, c’est parce qu’… elles n'ont pas eu de chance ?"
label variable pe6_cd_4 "PE6_CD_4. Si des personnes se trouvent en situation d’exclusion ou de pauvreté DEPUIS LA CRISE DU COVID, c’est parce qu’… il n'y a plus assez de travail pour tout le monde ?"
label variable pe7 "PE7. Selon vous, pour vivre, quel est le montant dont doit disposer AU MINIMUM un individu par mois (en euros) ?"
label variable pe16 "PE16. Selon vous, pour vivre, quel est le montant dont doit disposer AU MINIMUM un foyer comme le vôtre, par mois (en euros) ?"
label variable pe8 "PE8. D'après ce que vous en savez, quel est le montant du RSA pour une personne seule qui ne travaille pas (par mois en euros) ?"
label variable pe9_ab "PE9_AB. Avec laquelle de ces opinions sur le RSA êtes-vous le plus d’accord ?"
label variable pe9_cd "PE9_CD. DANS LE CONTEXTE DE CRISE DU COVID, avec laquelle de ces opinions sur le RSA êtes-vous le plus d’accord ?"
label variable pe10 "PE10. Dans ce cas, seriez-vous prêt à accepter une hausse de vos impôts ou de vos cotisations pour financer une augmentation du RSA ?"
label variable pe17_ab "PE17_AB. Sauf exception, on ne peut avoir le RSA qu'à partir de 25 ans. Êtes-vous favorable à son ouverture dès 18 ans ?"
label variable pe17_cd "PE17_CD. Sauf exception, on ne peut avoir le RSA qu’à partir de 25 ans. DANS LE CONTEXTE DE CRISE DU COVID, êtes-vous favorable à son ouverture dès 18 ans ?"
label variable pe11 "PE11. D'après ce que vous en savez, quel est le montant du SMIC net (par mois en euros) ?"
label variable pe12_ab "PE12_AB. Avec laquelle de ces opinions sur le SMIC êtes-vous le plus d’accord ?"
label variable pe12_cd "PE12_CD. DANS LE CONTEXTE DE CRISE DU COVID, avec laquelle de ces opinions sur le SMIC êtes-vous le plus d’accord ?"
label variable pe13_ab "PE13_AB. Selon vous, les allocations chômage doivent-elles être un droit limité dans le temps ?"
label variable pe13_cd "PE13_CD. Selon vous, EN CAS DE CRISE, les allocations chômage doivent-elles être un droit PROLONGE DURANT LA DURÉE DE LA CRISE ?"
label variable pe14_1 "PE14_1. Trouveriez-vous normal qu’on demande aux personnes qui touchent des allocations chômage… d’accepter les emplois correspondant à leurs qualifications et pas trop éloignés de leur domicile ?"
label variable pe14_2 "PE14_2. Trouveriez-vous normal qu’on demande aux personnes qui touchent des allocations chômage… d'accepter les emplois quels que soient la qualification et le lieu ?"
label variable pe14_3 "PE14_3. Trouveriez-vous normal qu’on demande aux personnes qui touchent des allocations chômage… d'accepter d'effectuer un stage de formation ?"
label variable pe14_4 "PE14_4. Trouveriez-vous normal qu’on demande aux personnes qui touchent des allocations chômage… de participer à une tâche d'intérêt général ?"
label variable pe15_ab "PE15_AB. Actuellement, compte tenu de votre situation globale, du montant des aides publiques et de vos impôts, vous considérez que…"
label variable pe15_cd "PE15_CD. DEPUIS LA CRISE DU COVID, compte tenu de votre situation globale, du montant des aides publiques et de vos impôts, vous considérez que…"
label variable pe18_ab "PE18_AB. En imaginant que vous deviez faire face à une dépense imprévue de 500 € dans l’année qui vient, pensez-vous…"
label variable pe18_cd "PE18_CD. En imaginant que vous deviez faire face AUJOURD’HUI à une dépense imprévue de 500 € pensez-vous... ?"
label variable lo1 "LO1. Concernant votre résidence principale, êtes-vous..."
label variable lo2 "LO2. Avez-vous un remboursement de prêt en cours pour votre résidence principale ?"
label variable lo10 "LO10. Combien avez-vous de PIECES D’HABITATION (ou de pièces habitables) dans votre résidence principale ?"
label variable re1_ab "RE1_AB. À l'heure actuelle, comment évaluez-vous le niveau de vie moyen des retraités par rapport à celui de l'ensemble de la population ?"
label variable re1_cd "RE1_CD. DEPUIS LA CRISE DU COVID, comment évaluez-vous le niveau de vie moyen des retraités par rapport à celui de l'ensemble de la population ?"
label variable re2 "RE2. Lorsque vous serez à la retraite, comment pensez-vous que votre niveau de vie sera par rapport à celui de l’ensemble de la population ?"
label variable re4 "RE4. Dans l'idéal, à quel âge souhaiteriez-vous ou auriez-vous aimé prendre votre retraite ?"
label variable re5 "RE5. À quel âge, d'après vous, pourrez-vous prendre votre retraite ?"
label variable re16 "RE16. À quel âge avez-vous pris votre retraite ?"
label variable re6 "RE6. À partir de quel âge estimez-vous qu'il n'est plus acceptable de faire travailler les gens ?"
label variable re9bis "RE9BIS. Pensez-vous que pour préserver le système de retraite par répartition tel qu’il existe…"
label variable re9_ac "RE9_AC. Parmi les solutions suivantes pour préserver le système de retraite par répartition tel qu'il existe, laquelle a votre préférence ?"
label variable re9_bd "RE9_BD. Parmi les solutions suivantes pour préserver le système de retraite par répartition tel qu'il existe, laquelle a votre préférence ?"
label variable re10 "RE10. À l'avenir, que faudrait-il faire en priorité en matière de retraite ?"
label variable fa1 "FA1. Selon vous, quel devrait être l'objectif prioritaire de la politique familiale ?"
label variable fa3 "FA3. En dehors des parents, quel mode de garde ou d’accueil vous semble le plus bénéfique pour un enfant en bas âge ?"
label variable fa4 "FA4. Quel est le mode de garde ou d'accueil que vous avez principalement utilisé pour vos enfants ?"
label variable fa5 "FA5. En ce qui concerne la garde des enfants, avec laquelle de ces deux propositions suivantes êtes-vous le plus d'accord ?"
label variable fa17 "FA17. Lorsqu'un des parents s'arrête de travailler ou réduit son temps de travail pour s'occuper de ses enfants, pensez-vous…"
label variable fa6 "FA6. Aujourd’hui le congé de maternité est de 16 semaines au premier et deuxième enfant et de 26 semaines à partir du troisième, pensez-vous que ces durées sont …"
label variable fa7 "FA7. En complément du congé de 3 jours au moment de la naissance, le congé paternité permet au père d’un enfant de bénéficier de 11 jours de congé. Selon vous, faut-il..."
label variable fa8 "FA8. Faut-il rendre le congé paternité obligatoire ?"
label variable fa9_ab_1 "FA9_AB_1. Souhaiteriez-vous ou auriez-vous souhaité recevoir de l’aide dans l’accompagnement de votre rôle de parent... dans vos relations avec l'école ?"
label variable fa9_ab_2 "FA9_AB_2. Souhaiteriez-vous ou auriez-vous souhaité recevoir de l’aide dans l’accompagnement de votre rôle de parent… pour gérer l'autorité, ce qu'il faut permettre ou interdire ?"
label variable fa9_ab_3 "FA9_AB_3. Souhaiteriez-vous ou auriez-vous souhaité recevoir de l’aide dans l’accompagnement de votre rôle de parent… sur les questions de santé ?"
label variable fa9_ab_4 "FA9_AB_4. Souhaiteriez-vous ou auriez-vous souhaité recevoir de l’aide dans l’accompagnement de votre rôle de parent... en cas de conflits familiaux et/ou de rupture ?"
label variable fa9_ab_5 "FA9_AB_5. Souhaiteriez-vous ou auriez-vous souhaité recevoir de l’aide dans l’accompagnement de votre rôle de parent... sur l'éveil et le développement du jeune enfant ?"
label variable fa9_cd_1 "FA9_CD_1. DURANT LE CONFINEMENT, auriez-vous souhaité recevoir de l’aide dans l’accompagnement de votre rôle de parent... dans vos relations avec l'école ?"
label variable fa9_cd_2 "FA9_CD_2. DURANT LE CONFINEMENT, auriez-vous souhaité recevoir de l’aide dans l’accompagnement de votre rôle de parent… pour gérer l'autorité, ce qu'il faut permettre ou interdire ?"
label variable fa9_cd_3 "FA9_CD_3. DURANT LE CONFINEMENT, auriez-vous souhaité recevoir de l’aide dans l’accompagnement de votre rôle de parent… sur les questions de santé ?"
label variable fa9_cd_4 "FA9_CD_4. DURANT LE CONFINEMENT, auriez-vous souhaité recevoir de l’aide dans l’accompagnement de votre rôle de parent... en cas de conflits familiaux et/ou de rupture ?"
label variable fa9_cd_5 "FA9_CD_5. DURANT LE CONFINEMENT, auriez-vous souhaité recevoir de l’aide dans l’accompagnement de votre rôle de parent... sur l'éveil et le développement du jeune enfant ?"
label variable fa10 "FA10. En cas de séparation des parents, quelle solution vous semble la plus satisfaisante pour la garde des enfants ?"
label variable fa18 "FA18. Après un divorce ou une séparation, lorsqu'il a été décidé qu'un des parents doit verser une pension alimentaire pour les enfants à l'autre parent. Pensez-vous…"
label variable fa19_ab "FA19_AB. Actuellement dans votre foyer, qui prend en charge les activités consacrées à votre ou vos enfants (repas, loisirs, éducation)?"
label variable fa19_cd "FA19_CD. DURANT LE CONFINEMENT, dans votre foyer, qui a pris en charge les activités consacrées à votre ou vos enfants (repas, loisirs, éducation)?"
label variable fa11_ab "FA11_AB. Actuellement, les allocations familiales sont versées aux familles d'au moins deux enfants. Avec laquelle de ces propositions êtes-vous le plus d'accord ?"
label variable fa11_cd "FA11_CD. Actuellement, les allocations familiales sont versées aux familles d'au moins deux enfants. DEPUIS LA CRISE DU COVID, Avec laquelle de ces propositions êtes-vous le plus d'accord ?"
label variable fa12 "FA12. Actuellement, le montant des allocations familiales augmente avec le rang de l’enfant. Avec laquelle de ces propositions êtes-vous le plus d’accord ?"
label variable fa13_ab "FA13_AB. Actuellement, le montant des allocations familiales dépend des ressources des familles. Selon-vous, il faut…"
label variable fa13_cd "FA13_CD. Actuellement, le montant des allocations familiales dépend des ressources des familles. Selon- vous, DEPUIS LA CRISE DU COVID, il faut…"
label variable fa14 "FA14. Êtes-vous favorables à ce que les couples homosexuels puissent adopter un enfant ?"
label variable fa15 "FA15. Êtes-vous favorables à ce que les couples de femmes puissent recourir à la procréation médicalement assistée pour avoir un enfant ?"
label variable fa16 "FA16. Êtes-vous favorable à ce que les couples hétérosexuels et/ou les couples homosexuels puissent recourir à la gestation pour autrui pour avoir un enfant ?"
label variable ha1 "HA1. À votre avis, la société actuelle se donne-t-elle les moyens d'intégrer les personnes handicapées ?"
label variable de1 "DE1. Selon vous, qui doit principalement prendre en charge financièrement les personnes âgées dépendantes ?"
label variable de4 "DE4. Seriez-vous prêt.e à épargner davantage en prévision d'une éventuelle situation de dépendance vous concernant ?"
label variable de5_ab "DE5_AB. Si l'un de vos parents proches devenait dépendant, que feriez-vous ?"
label variable de5_cd "DE5_CD. DEPUIS LA CRISE DU COVID, si l'un de vos parents proches devenait dépendant, que feriez-vous ?"
label variable de7 "DE7. Vous personnellement, apportez-vous une aide régulière et bénévole à une personne âgée dépendante vivant chez vous, chez elle ou ailleurs (institution…) ?"
label variable ps1_ab_1 "PS1_AB_1. À votre avis, l'assurance maladie devrait-elle bénéficier..."
label variable ps1_ab_2 "PS1_AB_2. À votre avis, les retraites devraient-elles bénéficier…"
label variable ps1_ab_3 "PS1_AB_3. À votre avis, les allocations familiales devraient-elles bénéficier..."
label variable ps1_ab_4 "PS1_AB_4. À votre avis, les allocations chômage devraient-elles bénéficier..."
label variable ps1_cd_1 "PS1_CD_1. À votre avis DEPUIS LA CRISE DU COVID, l'assurance maladie devrait-elle bénéficier..."
label variable ps1_cd_2 "PS1_CD_2. À votre avis DEPUIS LA CRISE DU COVID, les retraites devraient-elles bénéficier…"
label variable ps1_cd_3 "PS1_CD_3. À votre avis DEPUIS LA CRISE DU COVID, les allocations familiales devraient-elles bénéficier..."
label variable ps1_cd_4 "PS1_CD_4. À votre avis DEPUIS LA CRISE DU COVID, les allocations chômage devraient-elles bénéficier..."
label variable ps2_ab "PS2_AB. Actuellement, les entreprises cotisent pour la protection sociale. Avec laquelle des trois propositions suivantes, êtes-vous le plus d'accord ? À l'avenir..."
label variable ps2_cd "PS2_CD. Actuellement, les entreprises cotisent pour la protection sociale. Avec laquelle des trois propositions suivantes, êtes-vous le plus d'accord ? DEPUIS LA CRISE DU COVID ..."
label variable ps3_ab "PS3_AB. La France consacre environ le tiers du revenu national au financement de la protection sociale. Considérez-vous que c'est…"
label variable ps3_cd "PS3_CD. La France consacre environ le tiers du revenu national au financement de la protection sociale. DANS LE CONTEXTE DE CRISE DU COVID, considérez-vous que c'est…"
label variable ps13_a_1 "PS13_A_1. Accepteriez-vous une baisse de l'assurance maladie en échange d’une baisse de vos impôts ou de vos cotisations ?"
label variable ps13_a_2 "PS13_A_2. Accepteriez-vous une baisse des retraites en échange d’une baisse de vos impôts ou de vos cotisations ?"
label variable ps13_a_3 "PS13_A_3. Accepteriez-vous une baisse des allocations familiales en échange d’une baisse de vos impôts ou de vos cotisations ?"
label variable ps13_a_4 "PS13_A_4. Accepteriez-vous une baisse des allocations chômage en échange d’une baisse de vos impôts ou de vos cotisations ?"
label variable ps13_a_5 "PS13_A_5. Accepteriez-vous une baisse des aides aux personnes handicapées en échange d’une baisse de vos impôts ou de vos cotisations ?"
label variable ps13_a_6 "PS13_A_6. Accepteriez-vous une baisse des aides aux personnes âgées dépendantes en échange d’une baisse de vos impôts ou de vos cotisations ?"
label variable ps13_a_7 "PS13_A_7. Accepteriez-vous une baisse des allocations logement en échange d’une baisse de vos impôts ou de vos cotisations ?"
label variable ps13_b_1 "PS13_B_1. Accepteriez-vous une HAUSSE de vos impôts ou de vos cotisations POUR FINANCER LES REMBOURSEMENTS de l’assurance maladie ?"
label variable ps13_b_2 "PS13_B_2. Accepteriez-vous une HAUSSE de vos impôts ou de vos cotisations POUR FINANCER L'AUGMENTATION des retraites ?"
label variable ps13_b_3 "PS13_B_3. Accepteriez-vous une HAUSSE de vos impôts ou de vos cotisations POUR FINANCER L'AUGMENTATION des allocations familiales ?"
label variable ps13_b_4 "PS13_B_4. Accepteriez-vous une HAUSSE de vos impôts ou de vos cotisations POUR FINANCER L'AUGMENTATION des allocations chômage ?"
label variable ps13_b_5 "PS13_B_5. Accepteriez-vous une HAUSSE de vos impôts ou de vos cotisations POUR FINANCER L'AUGMENTATION des aides aux personnes handicapées ?"
label variable ps13_b_6 "PS13_B_6. Accepteriez-vous une HAUSSE de vos impôts ou de vos cotisations POUR FINANCER L'AUGMENTATION des aides aux personnes âgées dépendantes ?"
label variable ps13_b_7 "PS13_B_7. Accepteriez-vous une HAUSSE de vos impôts ou de vos cotisations POUR FINANCER L'AUGMENTATION des allocations logement ?"
label variable ps13_c_1 "PS13_C_1. EN CONTREPARTIE d’une baisse DES impôts ou DES cotisations, TROUVERIEZ-VOUS ACCEPTABLE DE DIMINUER  LES REMBOURSEMENTS de l’assurance maladie ?"
label variable ps13_c_2 "PS13_C_2. EN CONTREPARTIE d’une baisse DES impôts ou DES cotisations, TROUVERIEZ-VOUS ACCEPTABLE DE DIMINUER les retraites ?"
label variable ps13_c_3 "PS13_C_3. EN CONTREPARTIE d’une baisse DES impôts ou DES cotisations, TROUVERIEZ-VOUS ACCEPTABLE DE DIMINUER les allocations familiales ?"
label variable ps13_c_4 "PS13_C_4. EN CONTREPARTIE d’une baisse DES impôts ou DES cotisations, TROUVERIEZ-VOUS ACCEPTABLE DE DIMINUER les allocations chômage ?"
label variable ps13_c_5 "PS13_C_5. EN CONTREPARTIE d’une baisse DES impôts ou DES cotisations, TROUVERIEZ-VOUS ACCEPTABLE DE DIMINUER les aides aux personnes handicapées ?"
label variable ps13_c_6 "PS13_C_6. EN CONTREPARTIE d’une baisse DES impôts ou DES cotisations, TROUVERIEZ-VOUS ACCEPTABLE DE DIMINUER les aides aux personnes âgées dépendantes ?"
label variable ps13_c_7 "PS13_C_7. EN CONTREPARTIE d’une baisse DES impôts ou DES cotisations, TROUVERIEZ-VOUS ACCEPTABLE DE DIMINUER les allocations logement ?"
label variable ps13_d_1 "PS13_D_1. PARMI LES PRESTATIONS SUIVANTES, LESQUELLES VOUS SEMBLE-T-IL NÉCESSAIRE D’AUGMENTER, MÊME SI CELA IMPLIQUE UNE AUGMENTATION DES IMPÔTS OU DES COTISATIONS ? LES REMBOURSEMENTS de l’assurance maladie"
label variable ps13_d_2 "PS13_D_2. PARMI LES PRESTATIONS SUIVANTES, LESQUELLES VOUS SEMBLE-T-IL NÉCESSAIRE D’AUGMENTER, MÊME SI CELA IMPLIQUE UNE AUGMENTATION DES IMPÔTS OU DES COTISATIONS ? les retraites"
label variable ps13_d_3 "PS13_D_3. PARMI LES PRESTATIONS SUIVANTES, LESQUELLES VOUS SEMBLE-T-IL NÉCESSAIRE D’AUGMENTER, MÊME SI CELA IMPLIQUE UNE AUGMENTATION DES IMPÔTS OU DES COTISATIONS ? les allocations familiales"
label variable ps13_d_4 "PS13_D_4. PARMI LES PRESTATIONS SUIVANTES, LESQUELLES VOUS SEMBLE-T-IL NÉCESSAIRE D’AUGMENTER, MÊME SI CELA IMPLIQUE UNE AUGMENTATION DES IMPÔTS OU DES COTISATIONS ? les allocations chômage"
label variable ps13_d_5 "PS13_D_5. PARMI LES PRESTATIONS SUIVANTES, LESQUELLES VOUS SEMBLE-T-IL NÉCESSAIRE D’AUGMENTER, MÊME SI CELA IMPLIQUE UNE AUGMENTATION DES IMPÔTS OU DES COTISATIONS ? les aides aux personnes handicapées"
label variable ps13_d_6 "PS13_D_6. EPARMI LES PRESTATIONS SUIVANTES, LESQUELLES VOUS SEMBLE-T-IL NÉCESSAIRE D’AUGMENTER, MÊME SI CELA IMPLIQUE UNE AUGMENTATION DES IMPÔTS OU DES COTISATIONS ? les aides aux personnes âgées dépendantes"
label variable ps13_d_7 "PS13_D_7. PARMI LES PRESTATIONS SUIVANTES, LESQUELLES VOUS SEMBLE-T-IL NÉCESSAIRE D’AUGMENTER, MÊME SI CELA IMPLIQUE UNE AUGMENTATION DES IMPÔTS OU DES COTISATIONS ? les allocations logement"
label variable ps15_ab_1 "PS15_AB_1. « Notre système de sécurité sociale... fournit un niveau de protection suffisant »"
label variable ps15_ab_2 "PS15_AB_2. « Notre système de sécurité sociale... peut servir de modèle à d'autres pays »"
label variable ps15_ab_3 "PS15_AB_3. « Notre système de sécurité sociale... coûte trop cher à la société »"
label variable ps15_cd_1 "PS15_CD_1. « DANS UN CONTEXTE DE CRISE, notre système de sécurité sociale notre système de sécurité sociale... fournit un niveau de protection suffisant »"
label variable ps15_cd_2 "PS15_CD_2. « DANS UN CONTEXTE DE CRISE, notre système de sécurité sociale notre système de sécurité sociale... peut servir de modèle à d'autres pays »"
label variable ps15_cd_3 "PS15_CD_3. « DANS UN CONTEXTE DE CRISE, notre système de sécurité sociale notre système de sécurité sociale... coûte trop cher à la société »"
label variable ps18_ab "PS18_AB. En matière de politique sociale, quel type d’actions vous semble le plus nécessaire aujourd’hui ?"
label variable ps18_cd "PS18_CD. En matière de politique sociale, quel type d’actions vous semble le plus nécessaire DEPUIS LA CRISE DU COVID ?"
label variable ps16_ab "PS16_AB. Pour vous, quel est le plus important"
label variable ps16_cd "PS16_CD. Pour vous, DANS UN CONTEXTE DE CRISE, quel est le plus important"
label variable sa1_ab "SA1_AB. Comment est votre état de santé général ?"
label variable sa1_cd "SA1_CD. Comment est votre état de santé DEPUIS LA CRISE DU COVID ?"
label variable sa3_ac "SA3_AC. Êtes-vous limité.e depuis au moins 6 mois à cause d’un problème de santé, dans les activités que les gens font habituellement ?"
label variable sa3_bd "SA3_BD. Êtes-vous limité.e depuis au moins 6 mois à cause d’un problème de santé, dans les activités que les gens font habituellement ?"
label variable sa4 "SA4. Avez-vous une affection de longue durée, appelée aussi ALD, pour laquelle vos soins sont pris en charge à 100 % par l'Assurance maladie ou la Sécurité sociale ?"
label variable sa5 "SA5. Selon vous, au cours des dernières années, l'état de santé des Français s'est…"
label variable sa6_ab_1 "SA6_AB_1. « En France tout le monde peut être soigné quel que soit son revenu »"
label variable sa6_ab_2 "SA6_AB_2. « En France on a la même qualité de soins quel que soit son revenu »"
label variable sa6_ab_3 "SA6_AB_3. « En France tout le monde peut être soigné quel que soit le lieu où il habite »"
label variable sa6_ab_4 "SA6_AB_4. « En France on a la même qualité de soins quel que soit le lieu où l'on habite »"
label variable sa6_ab_5 "SA6_AB_5. « En France on a les mêmes délais d’attente pour se faire soigner quel que soit son revenu »"
label variable sa6_ab_6 "SA6_AB_6. « En France on a les mêmes délais d'attente pour se faire soigner quel que soit le lieu où l'on habite »"
label variable sa6_cd_1 "SA6_CD_1. « En France DURANT LE CONFINEMENT, tout le monde A PU être soigné quel que soit son revenu »"
label variable sa6_cd_2 "SA6_CD_2. « En France DURANT LE CONFINEMENT, On A EU la même qualité de soins quel que soit son revenu »"
label variable sa6_cd_3 "SA6_CD_3. « En France DURANT LE CONFINEMENT, tout le monde A PU être soigné quel que soit le lieu où il habite »"
label variable sa6_cd_4 "SA6_CD_4. « En France DURANT LE CONFINEMENT, on A EU la même qualité de soins quel que soit le lieu où l’on habite »"
label variable sa6_cd_5 "SA6_CD_5. « En France DURANT LE CONFINEMENT, on A EU les mêmes délais d’attente pour se faire soigner quel que soit son revenu »"
label variable sa6_cd_6 "SA6_CD_6. « En France DURANT LE CONFINEMENT, on A EU les mêmes délais d’attente pour se faire soigner quel que soit le lieu où l’on habite »"
label variable me4_ab "ME4_AB. Êtes-vous inquiet.e à l’idée de ne pas pouvoir être bien soigné en cas de gros problème de santé ?"
label variable me4_cd "ME4_ACD AVEZ-VOUS ÉTÉ inquiet.e DURANT LE CONFINEMENT à l’idée de ne pas pouvoir être bien soigné en cas de gros problème de santé ?"
label variable sa7_ab_1 "SA7_AB_1. En général, êtes-vous satisfait de la qualité des soins offerts par les … hôpitaux publics (hors services d'urgence et maternités) ?"
label variable sa7_ab_2 "SA7_AB_2. En général, êtes-vous satisfait de la qualité des soins offerts par les … urgences hospitalières ?"
label variable sa7_ab_3 "SA7_AB_3. En général, êtes-vous satisfait de la qualité des soins offerts par les … cliniques privées ?"
label variable sa7_ab_4 "SA7_AB_4. En général, êtes-vous satisfait de la qualité des soins offerts par les … dentistes, orthodontistes ?"
label variable sa7_ab_5 "SA7_AB_5. En général, êtes-vous satisfait de la qualité des soins offerts par les … médecins généralistes (hors hôpital) ?"
label variable sa7_ab_6 "SA7_AB_6. En général, êtes-vous satisfait de la qualité des soins offerts par les … médecins spécialistes (hors hôpital) ?"
label variable sa7_ab_7 "SA7_AB_7. En général, êtes-vous satisfait de la qualité des soins offerts par les … infirmiers/infirmières (hors hôpital) ?"
label variable sa7_ab_8 "SA7_AB_8. En général, êtes-vous satisfait de la qualité des soins offerts par les … maternités ?"
label variable sa7_cd_1 "SA7_CD_1. DEPUIS LA CRISE DU COVID, êtes-vous satisfait de la qualité des soins offerts par les … hôpitaux publics (hors services d'urgence et maternités) ?"
label variable sa7_cd_2 "SA7_CD_2. DEPUIS LA CRISE DU COVID, êtes-vous satisfait de la qualité des soins offerts par les … urgences hospitalières ?"
label variable sa7_cd_3 "SA7_CD_3. DEPUIS LA CRISE DU COVID, êtes-vous satisfait de la qualité des soins offerts par les … cliniques privées ?"
label variable sa7_cd_4 "SA7_CD_4. DEPUIS LA CRISE DU COVID, êtes-vous satisfait de la qualité des soins offerts par les … dentistes, orthodontistes ?"
label variable sa7_cd_5 "SA7_CD_5. DEPUIS LA CRISE DU COVID, êtes-vous satisfait de la qualité des soins offerts par les … médecins généralistes (hors hôpital) ?"
label variable sa7_cd_6 "SA7_CD_6. DEPUIS LA CRISE DU COVID, êtes-vous satisfait de la qualité des soins offerts par les … médecins spécialistes (hors hôpital) ?"
label variable sa7_cd_7 "SA7_CD_7. DEPUIS LA CRISE DU COVID, êtes-vous satisfait de la qualité des soins offerts par les … infirmiers/infirmières (hors hôpital) ?"
label variable sa7_cd_8 "SA7_CD_8. DEPUIS LA CRISE DU COVID, êtes-vous satisfait de la qualité des soins offerts par les … maternités ?"
label variable sa27 "SA27. Au cours des 12 derniers mois, avez-vous dû renoncer à un examen ou traitement médical dont vous aviez besoin ?"
label variable sa8_1 "SA8_1. Pour réduire le déficit de la branche maladie de la Sécurité sociale, seriez-vous plutôt favorable ou opposé.e à… augmenter les cotisations ?"
label variable sa8_2 "SA8_2. Pour réduire le déficit de la branche maladie de la Sécurité sociale, seriez-vous plutôt favorable ou opposé.e à… limiter le remboursement de la Sécurité sociale pour certaines prestations  ?"
label variable sa8_3 "SA8_3. Pour réduire le déficit de la branche maladie de la Sécurité sociale, seriez-vous plutôt favorable ou opposé.e à… réduire la prise en charge des longues maladies par la sécurité sociale ?"
label variable sa8_5 "SA8_5. Pour réduire le déficit de la branche maladie de la Sécurité sociale, seriez-vous plutôt favorable ou opposé.e à… modifier les habitudes des médecins pour qu’ils prescrivent moins de médicaments et d’examens ?"
label variable sa8_6 "SA8_6. Pour réduire le déficit de la branche maladie de la Sécurité sociale, seriez-vous plutôt favorable ou opposé.e à… limiter les tarifs des professionnels de santé ?"
label variable sa8_7 "SA8_7. Pour réduire le déficit de la branche maladie de la Sécurité sociale, seriez-vous plutôt favorable ou opposé.e à… taxer davantage les fabricants de médicaments ?"
label variable sa8_9 "SA8_9. Pour réduire le déficit de la branche maladie de la Sécurité sociale, seriez-vous plutôt favorable ou opposé.e à… permettre aux infirmiers / pharmaciens de faire certaines tâches à la place des médecins ?"
label variable sa9_1 "SA9_1. À votre avis, pensez-vous qu'il y a à proximité de chez vous des... médecins généralistes ?"
label variable sa9_2 "SA9_2. À votre avis, pensez-vous qu'il y a à proximité de chez vous des… médecins spécialistes ?"
label variable sa9_3 "SA9_3. À votre avis, pensez-vous qu'il y a à proximité de chez vous des... infirmiers / infirmières ?"
label variable sa9_4 "SA9_4. À votre avis, pensez-vous qu'il y a à proximité de chez vous des... kinésithérapeutes ?"
label variable sa9_5 "SA9_5. À votre avis, pensez-vous qu'il y a à proximité de chez vous des… dentistes ?"
label variable sa9_6 "SA9_6. À votre avis, pensez-vous qu'il y a à proximité de chez vous des… pharmaciens/pharmaciennes ?"
label variable sa13_ac_1 "SA13_AC_1. En cas de crise sanitaire, on peut selon vous avoir confiance dans ce que disent … les médecins ?"
label variable sa13_ac_2 "SA13_AC_2. En cas de crise sanitaire, on peut selon vous avoir confiance dans ce que disent … les chercheurs ?"
label variable sa13_ac_3 "SA13_AC_3. En cas de crise sanitaire, on peut selon vous avoir confiance dans ce que disent … les journalistes à la télévision ou la radio ?"
label variable sa13_ac_4 "SA13_AC_4. En cas de crise sanitaire, on peut selon vous avoir confiance dans ce que disent … les hommes et femmes politiques ?"
label variable sa13_ac_5 "SA13_AC_5. En cas de crise sanitaire, on peut selon vous avoir confiance dans ce que disent … les sites internet et les blogs spécialisés ?"
label variable sa13bis_ac "SA13bis_AC. En cas de crise sanitaire, on peut selon vous avoir confiance dans ce que disent … les réseaux sociaux ?"
label variable sa13_bd_1 "SA13_BD_1. En cas de crise sanitaire, on peut selon vous avoir confiance dans ce que disent … votre médecin (généraliste)"
label variable sa13_bd_2 "SA13_BD_2. En cas de crise sanitaire, on peut selon vous avoir confiance dans ce que disent … les chercheurs"
label variable sa13_bd_3 "SA13_BD_3. En cas de crise sanitaire, on peut selon vous avoir confiance dans ce que disent … les journalistes à la télévision ou la radio"
label variable sa13_bd_4 "SA13_BD_4. En cas de crise sanitaire, on peut selon vous avoir confiance dans ce que disent … les hommes et femmes politiques"
label variable sa13_bd_5 "SA13_BD_5. En cas de crise sanitaire, on peut selon vous avoir confiance dans ce que disent … les sites internet et les blogs spécialisés"
label variable sa13_bd_6 "SA13_BD_6. En cas de crise sanitaire, on peut selon vous avoir confiance dans ce que disent … les réseaux sociaux"
label variable sa16_1 "SA16_1. « Il n’y a pas de raison de limiter les dépenses car la santé n’a pas de prix »"
label variable sa16_2 "SA16_2. « Les dépenses de santé sont trop élevées car le système n'est pas bien géré »"
label variable sa16_3 "SA16_3. « Dans un pays développé, il est normal que l'on dépense de plus en plus pour la santé »"
label variable cs1_ab "CS1_AB. Selon vous, la cohésion sociale en France est-elle actuellement…"
label variable cs1_cd "CS1_CD. Selon vous, DEPUIS LA CRISE DU COVID, la cohésion sociale en France est-elle :"
label variable cs24_ab "CS24_AB. Selon vous, comment la solidarité entre les générations a-t-elle évolué au cours des dix dernières années ?"
label variable cs24_cd "CS24_CD. Selon vous, comment la solidarité entre les générations a-t-elle évolué DEPUIS LA CRISE DU COVID ?"
label variable cs4 "CS4. Auquel de ces lieux avez-vous personnellement le sentiment d'appartenir avant tout ?"
label variable cs5_ab "CS5_AB. Avez-vous le sentiment d’être intégré.e dans la société ?"
label variable cs5_cd "CS5_CD. Avez-vous le sentiment d’être intégré.e dans la société DEPUIS LA CRISE DU COVID ?"
label variable cs17 "CS17. Selon vous, les pouvoirs publics devraient-ils renforcer leur action pour soutenir l’intégration des personnes étrangères dans notre société ?"
label variable cs18_ab "CS18_AB. Estimez-vous que les pouvoirs publics font trop, font ce qu'ils doivent ou ne font pas assez pour les plus démunis ?"
label variable cs18_cd "CS18_CD. Estimez-vous que DEPUIS LA CRISE DU COVID les pouvoirs publics font trop, font ce qu’ils doivent ou ne font pas assez pour les plus démunis ?"
label variable cs25_1 "CS25_1. « La garde des jeunes enfants et le soutien aux parents » devraient être gérés…"
label variable cs25_2 "CS25_2. « L’autonomie des personnes âgées » devrait être gérée..."
label variable co3_1 "CO3_1. Pensez-vous que la crise du Covid a été bien gérée par ... le gouvernement"
label variable co3_2 "CO3_2. Pensez-vous que la crise du Covid a été bien gérée par ... les collectivités locales (commune, département, région)"
label variable cs19_1 "CS19_1. «  Beaucoup de personnes ne bénéficient pas des droits ou allocations auxquels elles peuvent prétendre  »"
label variable cs19_2 "CS19_2. «  Beaucoup de personnes perçoivent des allocations alors qu’elles n’y ont pas droit »"
label variable cs20 "CS20. Pour quelle raison principale pensez-vous que certaines personnes ne bénéficient pas d'allocations, droits, aides ou tarifs sociaux auxquels elles peuvent prétendre ?"
label variable cs14 "CS14. Quelle opinion se rapproche le plus de la vôtre ?"
label variable cs9 "CS9. Au cours des 12 derniers mois, avez-vous été le.la témoin de discriminations liées au fait d'être une femme ?"
label variable cs16_ac_1 "CS16_AC_1. Au cours des 12 derniers mois, avez-vous été le.la témoin d’une discrimination liée à l’origine ethnique"
label variable cs16_ac_2 "CS16_AC_2. Au cours des 12 derniers mois, avez-vous été le.la témoin d’une discrimination liée à l’orientation sexuelle"
label variable cs16_ac_3 "CS16_AC_3. Au cours des 12 derniers mois, avez-vous été le.la témoin d’une discrimination liée à l’âge"
label variable cs16_ac_4 "CS16_AC_4. Au cours des 12 derniers mois, avez-vous été le.la témoin d’une discrimination liée à  la religion"
label variable cs16_ac_5 "CS16_AC_5. Au cours des 12 derniers mois, avez-vous été le.la témoin d’une discrimination liée au handicap"
label variable cs16_bd_1 "CS16_BD_1. Au cours des 12 derniers mois, avez-vous été le.la témoin d’une discrimination liée à la couleur de peau"
label variable cs16_bd_2 "CS16_BD_2. Au cours des 12 derniers mois, avez-vous été le.la témoin d’une discrimination liée à l’orientation sexuelle"
label variable cs16_bd_3 "CS16_BD_3. Au cours des 12 derniers mois, avez-vous été le.la témoin d’une discrimination liée à l’âge"
label variable cs16_bd_4 "CS16_BD_4. Au cours des 12 derniers mois, avez-vous été le.la témoin d’une discrimination liée à  la religion"
label variable cs16_bd_5 "CS16_BD_5. Au cours des 12 derniers mois, avez-vous été le.la témoin d’une discrimination liée au handicap"
label variable cs22 "CS22. Selon vous, entre quels types de groupes les tensions seront-elles les plus fortes à l’avenir ?"
label variable sdassynd_1 "SDASSYND_1. Vous personnellement, êtes-vous membre d'une organisation syndicale ?"
label variable sdassynd_2 "SDASSYND_2. Vous personnellement, êtes-vous membre d'une association ?"
label variable sdrel "SDREL. Vis-à-vis de la religion, avez-vous…"
label variable sdproxim_1 "SDPROXIM_1. Dans votre famille ou en dehors de votre famille, connaissez-vous quelqu'un au chômage, indemnisé.e ?"
label variable sdproxim_2 "SDPROXIM_2. Dans votre famille ou en dehors de votre famille, connaissez-vous quelqu'un au chômage, non indemnisé.e ?"
label variable sdproxim_3 "SDPROXIM_3. Dans votre famille ou en dehors de votre famille, connaissez-vous quelqu'un qui est SDF ?"
label variable sdproxim_4 "SDPROXIM_4. Dans votre famille ou en dehors de votre famille, connaissez-vous quelqu'un élevant seul.e ses enfants avec un revenu inférieur au SMIC ?"
label variable sdproxim_5 "SDPROXIM_5. Dans votre famille ou en dehors de votre famille, connaissez-vous quelqu'un pensionné.e (invalide / handicapé.e) sans pouvoir travailler ?"
label variable sdproxim_6 "SDPROXIM_6. Dans votre famille ou en dehors de votre famille, connaissez-vous quelqu'un occupant un emploi précaire ?"
label variable sdproxim_7 "SDPROXIM_7. Dans votre famille ou en dehors de votre famille, connaissez-vous quelqu'un au RSA ?"
label variable sdproxim_8 "SDPROXIM_8. Dans votre famille ou en dehors de votre famille, connaissez-vous une personne handicapée de moins de 60 ans ?"
label variable sdproxim_9 "SDPROXIM_9. Dans votre famille ou en dehors de votre famille, connaissez-vous une personne âgée dépendante ?"
label variable sdrichom "SDRICHOM. Y a-t-il un risque de chômage dans les mois à venir pour vous-même ou l'un de vos proches ?"
label variable co4 "CO4. La situation financière de votre foyer a-t-elle changé DEPUIS LA CRISE DU COVID ?"
label variable sdres_1 "SDRES_1. Au cours des douze derniers mois, votre ménage a-t-il perçu des ressources provenant de salaires, traitements et primes ?"
label variable sdres_2 "SDRES_2. Au cours des douze derniers mois, votre ménage a-t-il perçu des ressources provenant de revenus d'une activité professionnelle indépendante ?"
label variable sdres_3 "SDRES_3. Au cours des douze derniers mois, votre ménage a-t-il perçu des ressources provenant du RSA (Revenu de solidarité active) ?"
label variable sdres_4 "SDRES_4. Au cours des douze derniers mois, votre ménage a-t-il perçu des ressources provenant des allocations de chômage ?"
label variable sdres_5 "SDRES_5. Au cours des douze derniers mois, votre ménage a-t-il perçu des ressources provenant de préretraite, retraites ?"
label variable sdres_6 "SDRES_6. Au cours des douze derniers mois, votre ménage a-t-il perçu des ressources provenant de revenus d'actifs financiers ?"
label variable sdres_7 "SDRES_7. Au cours des douze derniers mois, votre ménage a-t-il perçu des ressources provenant de revenus de locations ?"
label variable sdres_8 "SDRES_8. Au cours des douze derniers mois, votre ménage a-t-il perçu des ressources provenant de prestations familiales ?"
label variable sdres_9 "SDRES_9. Au cours des douze derniers mois, votre ménage a-t-il perçu des ressources provenant des allocations de logement ?"
label variable sdres_10 "SDRES_10. Au cours des douze derniers mois, votre ménage a-t-il perçu des ressources provenant de prestations liées au handicap, à l'invalidité ou à la dépendance ?"
label variable sdres_11 "SDRES_11. Au cours des douze derniers mois, votre ménage a-t-il perçu des ressources provenant de bourses d'études ?"
label variable sdres_12 "SDRES_12. Au cours des douze derniers mois, votre ménage a-t-il perçu des ressources provenant de pensions alimentaires ou argent reçu tous les mois de la part de proches ?"
label variable sdrevcl "SDREVCL. Revenus mensuels nets avant impôts"
label variable sdrevtr "SDREVTR. Revenus mensuels nets avant impôts du foyer (en tranches)"
label variable sdrevstab "SDREVSTAB. Globalement, diriez-vous que les revenus de votre foyer sont plutôt variables ou plutôt stables d’un mois sur l’autre ?"
label variable sdrevfut "SDREVFUT. Dans les mois qui viennent, pensez-vous que les revenus de votre foyer vont…"
label variable sddipl "SDDIPL. Niveau de diplôme"
label variable sddipl_det "SDDIPL_DET. Niveau de diplôme détaillé"
label variable sdpol "SDPOL. Sur une échelle de 0 à 10, où vous classeriez-vous politiquement ?"
label variable sdpoltr "SDPOLTR. Sur une échelle de 0 à 10, où vous classeriez-vous politiquement ?"
label variable sdnat "SDNAT. Nationalité"
label variable sdpnaistr "SDPNAISTR. Quel est votre pays de naissance ?"
label variable sdanfrtr "SDANFRTR. Vous êtes né.e à l'étranger, en quelle année êtes-vous arrivé en France ?"
label variable sdrevcl_imput   "SDREVCL_IMPUT. Revenu net mensuel"
label variable sdniviecl_imput "SDNIVIECL_IMPUT. Niveau de vie mensuel imputé"
label variable sdnivie "SDNIVIE. Quintiles de niveau de vie mensuel imputé"
label variable sdageenftr_1 "SDAGEENFTR_1. Nombre d'enfants à charge de 0 à 3 ans "
label variable sdageenftr_2 "SDAGEENFTR_2. Nombre d'enfants à charge de 4 à 6 ans "
label variable sdageenftr_3 "SDAGEENFTR_3. Nombre d'enfants à charge de 7 à 13 ans "
label variable sdageenftr_4 "SDAGEENFTR_4. Nombre d'enfants à charge de 14 à 17 ans "
label variable sdageenftr_5 "SDAGEENFTR_5. Nombre d'enfants à charge de 18 ans ou plus "
